window.__DATASTORE_PAYLOAD__ = {
  "portal_mode": "moabiz",
  "master": {
    "slug": "karen-residence-nishitakenotsuka",
    "registered_date": "2026-10-05",
    "updated_date": "2026-10-07",
    "public_enabled": true,
    "name_ko": "니시타케노츠카 2초메 카렌 레지던스",
    "name_ja": "西竹の塚2丁目 カレンレジデンス",
    "address_road": "東京都足立区西竹の塚2-4-36",
    "address_lot": "東京都足立区西竹の塚二丁目1325番29",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=%E6%9D%B1%E4%BA%AC%E9%83%BD%E8%B6%B3%E7%AB%8B%E5%8C%BA%E8%A5%BF%E7%AB%B9%E3%81%AE%E5%A1%9A2-4-36",
    "price_yen": 330000000,
    "price_display_ko": "3억 3,000만 엔",
    "consumption_tax_note": "소비세 포함 (税込 — 신축 건물분 소비세 포함가)",
    "transaction_type": "중개 (仲介)",
    "delivery_condition": "상담 (相談 — 현황 전 12호 공실 모집 중)",
    "land_area_sqm": 384.62,
    "land_area_tsubo": 116.35,
    "land_right": "소유권 (所有権)",
    "land_category": "택지 (宅地 — 소규모주택용지 12호×200㎡ 한도 내 100% 1/6·1/3 감면 특례 대상)",
    "topography": "평탄지 · 노지상부지 (平坦地・路地状敷地［旗竿地］)",
    "city_planning": "시가화구역 (市街化区域)",
    "zoning": "근린상업지역 (近隣商業地域)",
    "bcr_legal_pct": 80.0,
    "far_legal_pct": 240.0,
    "bcr_actual_pct": 54.35,
    "far_actual_pct": 157.34,
    "fire_zone": "[미수집] (근린상업지역 내 준방화지역 추정 — 건축확인대장 확인 필요)",
    "road_access": "북측 폭 약 4.00m 공도(42조 1항 1호 도로)에 약 3.0m 접면 (노지상부지/깃대형 토지)",
    "private_road_burden": "없음 (42조 1항 1호 공도 접면)",
    "structure_code": "WOOD",
    "structure_display": "목조 지상 3층 건 (木造3階建 · 열화등급 3급 상당 증명서 유)",
    "built_year_month": "2026년 10월 (令和8年10月 표기 / 포털 2026년 8월 준공 모집 중)",
    "building_age_years": 0.0,
    "statutory_life_years": 22,
    "remaining_life_years": 22.0,
    "bldg_area_reg_sqm": 605.17,
    "bldg_area_cert_sqm": 605.17,
    "total_units": 12,
    "unit_composition": "1LDK(32.78~33.01㎡)×5호 + 1DK(32.57㎡)×1호 [1층] + 2LDK 메조네트(70.48~71.76㎡, 임대도면 면적 미기재)×6호 [2~3층]",
    "parking_info": "주륜장 12개소 유 (駐輪場12ヶ所あり — 자동차 주차장 없음)",
    "has_confirm_cert": "보유 확실 (2026년 신축 — 단, 용도가 『나가야』인지 『공동주택』인지 사본 확인 필수)",
    "has_inspection_cert": "보유 확실 (2026년 신축 — 준공검사필증 및 열화등급 3급 상당 증명서 원본 징구 필수)",
    "utilities_gas": "LP가스 (プロパンガス — ⚠️ 도쿄 23구 역세권임에도 시공사 그룹 LP가스 채택, 무상대여 유무 확인 필수)",
    "utilities_water_sewer": "공영수도 · 공공하수 (公営水道・公共下水)",
    "has_elevator": "없음 (목조 3층 — 2·3층 세대는 1층 현관부터 내부 전용계단 2개소 이용)",
    "repair_history_summary": "신축 (2026년 준공 — 시공사 하우스링크홈(주) 초기 하자보수 보증 및 10년 하자담보책임 대상)",
    "current_occupied_units": 0,
    "current_annual_income_yen": 21768000,
    "full_annual_income_yen": 21768000,
    "gross_yield_current_pct": 6.6,
    "gross_yield_full_pct": 6.6,
    "disclosed_opex_yen": "[미수집] (신축 미과세 상태 — 본 분석에서 정규화 OPEX 연 366.4만~377.3만 엔 산출)",
    "normalized_opex_yen": 3668400,
    "opex_ratio_pct": 16.85,
    "noi_full_yen": 17011200,
    "cap_rate_full_pct": 5.15,
    "roadside_price_sqm": 382500,
    "assessed_land_yen": 147117150,
    "assessed_bldg_yen": 102878900,
    "assessed_ratio_pct": 75.76,
    "fixed_tax_land_eval_yen": 128727506,
    "fixed_tax_bldg_eval_yen": 59306660,
    "fixed_tax_annual_yen": 1320000,
    "loan_ltv_pct": 80.0,
    "loan_amount_yen": 264000000,
    "loan_rate_pct": 2.2,
    "loan_term_years": 30,
    "ads_annual_yen": 12028923,
    "pretax_cf_yen": 4982277,
    "posttax_cf_yen": 3348463,
    "dscr": 1.41,
    "icr": 2.14,
    "breakeven_occ_pct": 72.1,
    "allowable_vacant_units": 3.3,
    "initial_equity_yen": 91219000,
    "ccr_pct": 5.46,
    "station_access_summary": "도부 스카이트리 라인(도쿄메트로 히비야선 직통) 『타케노츠카(竹ノ塚)』역 서구 도보 3분 (포털 표기 3~4분)",
    "walk_min_disclosed": 3,
    "walk_min_gmaps": 4,
    "walk_dist_gmaps_m": 270,
    "walk_slope_note": "타케노츠카역 서구~세이유 앞을 지나는 완전 평탄한 근린상업지역 동선",
    "google_maps_walk_url": "https://www.google.com/maps/dir/%E7%AB%B9%E3%83%8E%E5%A1%9A%E9%A7%85/%E6%9D%B1%E4%BA%AC%E9%83%BD%E8%B6%B3%E7%AB%8B%E5%8C%BA%E8%A5%BF%E7%AB%B9%E3%81%AE%E5%A1%9A2-4-36/",
    "hazard_flood": "아다치구 홍수 해저드맵(아라카와 범람) 예상 침수심 0.5m~3.0m 미만 구역 (1층 침수 가능 — 수재보험 특약 필수)",
    "hazard_landslide": "해당 없음 (평탄한 저지대 상업·주거지역 — 토사재해 경계구역 외)",
    "homes_archive_url": "https://www.homes.co.jp/archive/b-51908415/",
    "avg_dom_days": 60,
    "turnover_vacancy_pct": 5.0,
    "rent_upside_annual_yen": -2100000,
    "score_price": 2.8,
    "score_demand": 3.9,
    "score_competition": 2.9,
    "score_future": 3.6,
    "score_cf": 3.3,
    "score_legal": 3.1,
    "score_total": 19.6,
    "verdict_short": "C+ 등급 (61/100점 | 19.6/30점) — 오카다부동산(임대부·대주) 확정 모집도면 기준 만실 연수입 2,176.8만 엔(표면 6.60% / 관리비 제외 시 2,119.2만 엔·6.42%)으로 매매 마이소쿠(연 2,386.8만 엔·7.23%) 대비 연 -210.0만 엔(관리비 제외 시 -267.6만 엔) 하향 확정(2LDK 전 6호 호당 월 -2만 엔 인하, 106호 1DK 확정, AD100%+FR1개월 전용가). 호가 3.30억 엔 매수 보류 · 2.90억~2.95억 엔(모집가 기준 표면 7.38%~7.51%) 지가 네고 + 30년 융자 + 만실 인도/마스터리스 특약 조건부 매수(Conditional Buy)",
    "verdict_badge": "조건부 매수 (2.95억 네고·리스업보증 필수)",
    "moabiz_verdict": "조건부 적합 (오카다부동산 확정 모집가 연 2,176.8만 엔[6.60%] 반영 · 30년 융자 시 통합 상환연수 33.2→25.3년[네고시 23.9년] 및 세무 LTV 263→198~210% 대폭 개선 / 단, 2.95억 엔 이하 네고 및 30년 융자·만실보증 필수)",
    "public_verdict": "조건부 매수 (61 / 100점 — 오카다부동산 확정 모집가[연 2,176.8만 엔·표면 6.60%, 임대료만 6.42%] 반영 2.90억~2.95억 엔 네고 및 30년 융자 필수)",
    "collection_rate_pct": 77.1,
    "collected_count": 27,
    "estimated_count": 3,
    "missing_count": 5,
    "data_stage_badge": "PARTIAL_DD (일부서류입수)"
  },
  "rent_roll": [
    {
      "room_no": "101",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1LDK (LDK9첩+양4.5첩)",
      "area_sqm": 33.01,
      "area_tsubo": 9.99,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 120000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 124000,
      "market_target_rent_yen": 124000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "오카다부동산 모집도면 확정 (12.0만+관리비 4천엔 / 예금1·멘테상각1·AD100%+FR1M)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "102",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1LDK (LDK9첩+양4.5첩)",
      "area_sqm": 33.01,
      "area_tsubo": 9.99,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 118000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 122000,
      "market_target_rent_yen": 122000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "오카다부동산 모집도면 확정 (11.8만+관리비 4천엔 / 예금1·멘테상각1·AD100%+FR1M)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "103",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1LDK (LDK9첩+양4.5첩)",
      "area_sqm": 33.01,
      "area_tsubo": 9.99,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 118000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 122000,
      "market_target_rent_yen": 122000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "오카다부동산 모집도면 확정 (11.8만+관리비 4천엔 / 예금1·멘테상각1·AD100%+FR1M)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "104",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1LDK (LDK9첩+양4.5첩)",
      "area_sqm": 33.01,
      "area_tsubo": 9.99,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 118000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 122000,
      "market_target_rent_yen": 122000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "오카다부동산 모집도면 확정 (11.8만+관리비 4천엔 / 예금1·멘테상각1·AD100%+FR1M)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "105",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1LDK (LDK8첩+양5첩)",
      "area_sqm": 32.78,
      "area_tsubo": 9.92,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 115000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 119000,
      "market_target_rent_yen": 119000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "오카다부동산 모집도면 확정 (11.5만+관리비 4천엔 / 예금1·멘테상각1·AD100%+FR1M)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "106",
      "floor": 1,
      "usage": "주거 (住宅)",
      "layout": "1DK (DK7첩+양5첩)",
      "area_sqm": 32.57,
      "area_tsubo": 9.85,
      "occupancy_status": "공실 (선행모집·시공중)",
      "tenant_type": "미입주 (9월 하순~ 계약개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 116000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 120000,
      "market_target_rent_yen": 120000,
      "rent_gap_upside_yen": 0,
      "estimated_dom_days": 45,
      "note": "⚠️ 매매마이소쿠 1LDK 표기이나 오카다 모집도면상 1DK(DK7첩+양5첩) 확정 (11.6만+4천엔)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "201",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F LDK12.2첩+3F 양5.6·7.5첩)",
      "area_sqm": 70.48,
      "area_tsubo": 21.32,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 180000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 184000,
      "market_target_rent_yen": 184000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(20.0만) 대비 -2.0만엔 인하 확정 (18.0만+4천엔 / 임대도면 면적 미기재)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "202",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F LDK12.2첩+3F 양5.6·7.5첩)",
      "area_sqm": 70.48,
      "area_tsubo": 21.32,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 175000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 179000,
      "market_target_rent_yen": 179000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(19.5만) 대비 -2.0만엔 인하 확정 (17.5만+4천엔 / 임대도면 면적 미기재)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "203",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F LDK12.2첩+3F 양5.6·7.5첩)",
      "area_sqm": 70.48,
      "area_tsubo": 21.32,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 175000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 179000,
      "market_target_rent_yen": 179000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(19.5만) 대비 -2.0만엔 인하 확정 (17.5만+4천엔 / 임대도면 면적 미기재)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "204",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F LDK12.2첩+3F 양5.6·7.5첩)",
      "area_sqm": 70.48,
      "area_tsubo": 21.32,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 175000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 179000,
      "market_target_rent_yen": 179000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(19.5만) 대비 -2.0만엔 인하 확정 (17.5만+4천엔 / 임대도면 면적 미기재)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "205",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F 양5.4·7.4첩+3F LDK18.1첩)",
      "area_sqm": 70.93,
      "area_tsubo": 21.46,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 176000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 180000,
      "market_target_rent_yen": 180000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(19.6만) 대비 -2.0만엔 인하 확정 (17.6만+4천엔 / 3층 18.1첩 LDK 배치)",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "room_no": "206",
      "floor": 2,
      "usage": "주거 (住宅)",
      "layout": "2LDK 메조네트 (2F LDK14.1첩+3F 양5·7.4첩)",
      "area_sqm": 71.76,
      "area_tsubo": 21.71,
      "occupancy_status": "공실 (완성전·선행모집)",
      "tenant_type": "미입주 (10월 상순~ 개시)",
      "contract_start_date": "-",
      "tenure_years": 0.0,
      "monthly_rent_yen": 180000,
      "monthly_common_fee_yen": 4000,
      "monthly_other_yen": 0,
      "monthly_total_yen": 184000,
      "market_target_rent_yen": 184000,
      "rent_gap_upside_yen": -20000,
      "estimated_dom_days": 75,
      "note": "⚠️ 매매마이소쿠(20.0만) 대비 -2.0만엔 인하 확정 (18.0만+4천엔 / 3층 욕실·세면실 배치)",
      "slug": "karen-residence-nishitakenotsuka"
    }
  ],
  "collection_audit": [
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_01",
      "category": "1.기본/가격",
      "field_key": "name_ko",
      "item_name_ko": "물건명 (한/일)",
      "item_name_ja": "物件名称",
      "collected_value": "니시타케노츠카 2초메 카렌 레지던스",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_02",
      "category": "1.기본/가격",
      "field_key": "address_road",
      "item_name_ko": "소재지 도로명주소 (住居表示)",
      "item_name_ja": "住居表示",
      "collected_value": "東京都足立区西竹の塚2-4-36",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_03",
      "category": "1.기본/가격",
      "field_key": "address_lot",
      "item_name_ko": "토지 지번 (地番)",
      "item_name_ja": "土地地番",
      "collected_value": "東京都足立区西竹の塚二丁目1325番29",
      "status": "COLLECTED",
      "source_doc": "등기부/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_04",
      "category": "1.기본/가격",
      "field_key": "price_yen",
      "item_name_ko": "매매가격 및 소비세 조건",
      "item_name_ja": "売買価格・消費税",
      "collected_value": "330000000",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_05",
      "category": "1.기본/가격",
      "field_key": "delivery_condition",
      "item_name_ko": "인도조건 및 계약부적합책임 면책 여부",
      "item_name_ja": "引渡条件・契約不適合免責",
      "collected_value": "상담 (相談 — 현황 전 12호 공실 모집 중)",
      "status": "COLLECTED",
      "source_doc": "물건개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_06",
      "category": "2.토지/도계",
      "field_key": "land_area_sqm",
      "item_name_ko": "토지 공부면적 (㎡/평)",
      "item_name_ja": "土地公簿面積",
      "collected_value": "384.62",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_07",
      "category": "2.토지/도계",
      "field_key": "land_right",
      "item_name_ko": "토지 권리형태 및 지목",
      "item_name_ja": "土地権利・地目",
      "collected_value": "소유권 (所有権)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_08",
      "category": "2.토지/도계",
      "field_key": "zoning",
      "item_name_ko": "용도지역 및 법정 건폐율·용적률",
      "item_name_ja": "用途地域・建蔽率・容積率",
      "collected_value": "근린상업지역 (近隣商業地域)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_09",
      "category": "2.토지/도계",
      "field_key": "road_access",
      "item_name_ko": "도로 접도 방위·폭원·접도길이",
      "item_name_ja": "接道状況（幅員・間口）",
      "collected_value": "북측 폭 약 4.00m 공도(42조 1항 1호 도로)에 약 3.0m 접면 (노지상부지/깃대형 토지)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/도로대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_10",
      "category": "2.토지/도계",
      "field_key": "private_road_burden",
      "item_name_ko": "사도부담 및 굴착·통행승낙서 유무",
      "item_name_ja": "私道負担・掘削通行承諾",
      "collected_value": "없음 (42조 1항 1호 공도 접면)",
      "status": "COLLECTED",
      "source_doc": "물건개요서/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_11",
      "category": "3.건물/적법",
      "field_key": "structure_display",
      "item_name_ko": "건물 구조 및 층수",
      "item_name_ja": "建物構造・規模",
      "collected_value": "목조 지상 3층 건 (木造3階建 · 열화등급 3급 상당 증명서 유)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_12",
      "category": "3.건물/적법",
      "field_key": "built_year_month",
      "item_name_ko": "신축 준공년월 및 경과연수",
      "item_name_ja": "築年月",
      "collected_value": "2026년 10월 (令和8年10月 표기 / 포털 2026년 8월 준공 모집 중)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_13",
      "category": "3.건물/적법",
      "field_key": "bldg_area_reg_sqm",
      "item_name_ko": "등기 연면적 vs 확인대장 연면적",
      "item_name_ja": "延床面積（登記・確認台帳）",
      "collected_value": "605.17",
      "status": "COLLECTED",
      "source_doc": "등기부/건축확인대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_14",
      "category": "3.건물/적법",
      "field_key": "has_confirm_cert",
      "item_name_ko": "건축확인필증(確認済証) 및 대장 유무",
      "item_name_ja": "建築確認済証・台帳記載事項証明",
      "collected_value": "보유 확실 (2026년 신축 — 단, 용도가 『나가야』인지 『공동주택』인지 사본 확인 필수)",
      "status": "COLLECTED",
      "source_doc": "건축확인대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_15",
      "category": "3.건물/적법",
      "field_key": "has_inspection_cert",
      "item_name_ko": "준공검사필증(検査済証) 취득 여부",
      "item_name_ja": "検査済証の有無",
      "collected_value": "보유 확실 (2026년 신축 — 준공검사필증 및 열화등급 3급 상당 증명서 원본 징구 필수)",
      "status": "COLLECTED",
      "source_doc": "검사필증/대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_16",
      "category": "3.건물/적법",
      "field_key": "repair_history_summary",
      "item_name_ko": "외벽도장·옥상방수 등 대규모 수선이력",
      "item_name_ja": "大規模修繕履歴（外壁・屋上防水）",
      "collected_value": "신축 (2026년 준공 — 시공사 하우스링크홈(주) 초기 하자보수 보증 및 10년 하자담보책임 대상)",
      "status": "COLLECTED",
      "source_doc": "수선이력서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_17",
      "category": "4.렌트롤",
      "field_key": "full_annual_income_yen",
      "item_name_ko": "호실별 월 차임 및 공익비 내역",
      "item_name_ja": "各戸賃料・共益費一覧",
      "collected_value": "21768000",
      "status": "VERIFIED",
      "source_doc": "렌트롤",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_18",
      "category": "4.렌트롤",
      "field_key": "unit_composition",
      "item_name_ko": "호실별 전유면적(㎡) 및 평형 타입",
      "item_name_ja": "各戸専有面積・間取り",
      "collected_value": "1LDK(32.78~33.01㎡)×5호 + 1DK(32.57㎡)×1호 [1층] + 2LDK 메조네트(70.48~71.76㎡, 임대도면 면적 미기재)×6호 [2~3층]",
      "status": "COLLECTED",
      "source_doc": "렌트롤/도면",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_19",
      "category": "4.렌트롤",
      "field_key": "rent_roll_contract_dates",
      "item_name_ko": "호실별 계약시작일(契約始期) 및 갱신주기",
      "item_name_ja": "各戸の契約始期・更新時期",
      "collected_value": "[미수집 - 계약시작일 미기재]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "렌트롤상 호실별 최초 계약시작일(입주일) 기재본 요청",
      "broker_inquiry_ja": "レントロールにおける各戸の契約始期（入居年月）のご教示"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_20",
      "category": "4.렌트롤",
      "field_key": "rent_roll_tenant_types",
      "item_name_ko": "호실별 입주자 속성(법인/직장인/학생/보증회사)",
      "item_name_ja": "入居者属性・保証会社加入状況",
      "collected_value": "속성 확인 (12실)",
      "status": "COLLECTED",
      "source_doc": "렌트롤 상세판",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_21",
      "category": "4.렌트롤",
      "field_key": "parking_info",
      "item_name_ko": "주차장·자판기·안테나 등 부대수입 계약현황",
      "item_name_ja": "駐車場・付帯収入の契約状況",
      "collected_value": "주륜장 12개소 유 (駐輪場12ヶ所あり — 자동차 주차장 없음)",
      "status": "COLLECTED",
      "source_doc": "렌트롤/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_22",
      "category": "5.경비/세금",
      "field_key": "disclosed_opex_yen",
      "item_name_ko": "PM 관리위탁비 및 정기청소비 실비",
      "item_name_ja": "PM管理委託費・定期清掃費",
      "collected_value": "[미수집]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "현재 위탁 중인 PM 관리수수료율 및 정기청소비 월액 확인",
      "broker_inquiry_ja": "現行のPM管理委託料率および定期清掃費等のランニングコスト明細のご共有"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_23",
      "category": "5.경비/세금",
      "field_key": "utilities_water_sewer",
      "item_name_ko": "공용 전기·수도·정화조·인터넷 유지비",
      "item_name_ja": "共用光熱費・浄化槽・ネット費用",
      "collected_value": "공영수도 · 공공하수 (公営水道・公共下水)",
      "status": "COLLECTED",
      "source_doc": "런닝코스트 명세",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_24",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_land_eval_yen",
      "item_name_ko": "고정자산세 토지 과세평가액",
      "item_name_ja": "固定資産税評価額（土地）",
      "collected_value": "128727506",
      "status": "ESTIMATED",
      "source_doc": "표준산식 역산 추정",
      "broker_inquiry_ko": "최신 연도 고정자산세·도시계획세 과세명세서(토지 평가액) 사본 요청",
      "broker_inquiry_ja": "最新年度の固定資産税・都市計画税課税明細書（土地評価額）の写しのご共有"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_25",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_bldg_eval_yen",
      "item_name_ko": "고정자산세 건물 과세평가액",
      "item_name_ja": "固定資産税評価額（建物）",
      "collected_value": "59306660",
      "status": "ESTIMATED",
      "source_doc": "표준산식 역산 추정",
      "broker_inquiry_ko": "최신 연도 고정자산세·도시계획세 과세명세서(건물 평가액) 사본 요청",
      "broker_inquiry_ja": "最新年度の固定資産税・都市計画税課税明細書（建物評価額）の写しのご共有"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_26",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_annual_yen",
      "item_name_ko": "고정자산세·도시계획세 연간 실납부세액",
      "item_name_ja": "固都税 年間納付税額",
      "collected_value": "1320000",
      "status": "ESTIMATED",
      "source_doc": "표준산식 역산 추정",
      "broker_inquiry_ko": "고정자산세·도시계획세 연간 납부세액 확정치 확인",
      "broker_inquiry_ja": "固定資産税・都市計画税の年間納付税額（確定値）のご教示"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_27",
      "category": "6.등기/내력",
      "field_key": "registry_owner_match",
      "item_name_ko": "토지·건물 등기부 소유자 일치 여부",
      "item_name_ja": "土地・建物登記簿の所有者一致",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "토지 및 건물 등기사항전부증명서(전부사항) 사본 요청",
      "broker_inquiry_ja": "土地・建物の全部事項証明書（登記簿謄本）のご共有"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_28",
      "category": "6.등기/내력",
      "field_key": "registry_history_갑구",
      "item_name_ko": "과거 소유권 변천내력(갑구) 및 매각동기",
      "item_name_ja": "所有権移転履歴・売却理由",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "현 소유자의 취득 경위 및 금번 매각 사유 확인",
      "broker_inquiry_ja": "現所有者様の取得経緯および今回のご売却理由のご教示"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_29",
      "category": "6.등기/내력",
      "field_key": "registry_liens_을구",
      "item_name_ko": "담보권·근저당·압류·지역권 유무(을구)",
      "item_name_ja": "抵当権・地役権等の権利関係",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "등기부 을구 권리관계 및 말소 조건 확인",
      "broker_inquiry_ja": "登記簿乙区の権利関係および引渡時抹消条件の確認"
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_30",
      "category": "7.외부실사",
      "field_key": "roadside_price_sqm",
      "item_name_ko": "국세청 상속세 노선가(路線価) 조회",
      "item_name_ja": "相続税路線価",
      "collected_value": "382500",
      "status": "VERIFIED",
      "source_doc": "국세청 노선가도",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_31",
      "category": "7.외부실사",
      "field_key": "walk_min_gmaps",
      "item_name_ko": "Google Maps 실측 도보거리 및 소요시간",
      "item_name_ja": "Googleマップ実測徒歩距離・時間",
      "collected_value": "4",
      "status": "VERIFIED",
      "source_doc": "Google Maps",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_32",
      "category": "7.외부실사",
      "field_key": "walk_slope_note",
      "item_name_ko": "보행 동선 고저차(경사/계단) 및 혐오시설 실사",
      "item_name_ja": "徒歩経路の高低差・周辺嫌悪施設",
      "collected_value": "타케노츠카역 서구~세이유 앞을 지나는 완전 평탄한 근린상업지역 동선",
      "status": "VERIFIED",
      "source_doc": "Google 스트리트뷰",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_33",
      "category": "7.외부실사",
      "field_key": "hazard_flood",
      "item_name_ko": "지자체 홍수·내수 침수 해저드맵 검증",
      "item_name_ja": "洪水・内水浸水ハザードマップ",
      "collected_value": "아다치구 홍수 해저드맵(아라카와 범람) 예상 침수심 0.5m~3.0m 미만 구역 (1층 침수 가능 — 수재보험 특약 필수)",
      "status": "VERIFIED",
      "source_doc": "지자체 하저드맵",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_34",
      "category": "7.외부실사",
      "field_key": "hazard_landslide",
      "item_name_ko": "토사재해 경계구역(옐로/레드존) 검증",
      "item_name_ja": "土砂災害警戒区域（イエロー/レッド）",
      "collected_value": "해당 없음 (평탄한 저지대 상업·주거지역 — 토사재해 경계구역 외)",
      "status": "VERIFIED",
      "source_doc": "지자체 하저드맵",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "karen-residence-nishitakenotsuka",
      "check_id": "CHK_35",
      "category": "7.외부실사",
      "field_key": "avg_dom_days",
      "item_name_ko": "LIFULL HOME'S 아카이브 과거 모집이력(DOM)",
      "item_name_ja": "HOME'S過去の掲載履歴・DOM分析",
      "collected_value": "60",
      "status": "VERIFIED",
      "source_doc": "LIFULL HOME'S",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    }
  ],
  "corporate_landing": {
    "standalone": {
      "price": 330000000.0,
      "loan": 264000000.0,
      "tax_land": 128727506.0,
      "tax_bldg": 59306660.0,
      "gross_income": 21768000.0,
      "opex": 3668400.0,
      "depr": 4676313.636363637,
      "ads": 12028923.0,
      "interest": 5808000.000000001,
      "principal": 6220922.999999999,
      "pretax_profit": 6526886.363636363,
      "pretax_cf": 4982277.0,
      "tax": 1631721.5909090908,
      "posttax_cf": 3350555.409090909,
      "debt_years": 32.9,
      "icr": 2.93,
      "dscr": 1.41,
      "ltv_tax": 1.404,
      "roi": 0.0367
    },
    "baseline": {
      "baseline_id": "moabiz_4th_term",
      "name_ko": "모아비즈 4기현재",
      "name_ja": "モアビズ4期現在",
      "price": 267538767,
      "loan": 240729467,
      "tax_land": 71857096,
      "tax_bldg": 41905687,
      "tax_total": 113762783,
      "gross_income": 16929000,
      "opex": 2539350,
      "depr": 7188563,
      "ads": 12647749,
      "interest": 8123958,
      "principal": 4523791,
      "pretax_profit": 3722450,
      "pretax_cf": 1741901,
      "pretax_cf_yield": 0.0065,
      "tax": 930613,
      "posttax_cf": 811289,
      "posttax_cf_yield": 0.003,
      "debt_years": 24.1,
      "easy_cf": 811289,
      "icr": 0.9,
      "dscr": 1.5,
      "ltv_tax": 2.6108,
      "roi": 0.0383
    },
    "combined": {
      "pretax_profit": 10249336.363636363,
      "pretax_cf": 6724178.0,
      "posttax_cf": 4161844.409090909,
      "debt_years": 31.5,
      "icr": 2.25,
      "dscr": 1.27,
      "ltv_tax": 1.6724,
      "roi": 0.0353
    }
  },
  "key_highlights": {
    "positives_ko": [
      "도부 스카이트리 라인(도쿄메트로 히비야선 직통·당역 시발 다수) 『타케노츠카』역 서구 도보 3분 — 2022년 고가화 완공 및 2024년 5월 역사 상업시설 『EQUiA 타케노츠카』 개업으로 역세권 가치 상승",
      "근린상업지역(건폐율 80%/기준용적률 240%) 토지 384.62㎡(116.35평) + 신축 연면적 605.17㎡(183.06평) 대형 볼륨으로 노지상 보정(-15%) 후에도 은행 표준 적산가 약 2억 5,000만 엔(호가 대비 75.8%, 네고가 2.95억 대비 84.7%) 확보",
      "오카다부동산 모집도면(전 7매)을 통해 전 호실 에어컨 완비(1층 각 2대·2~3층 각 3대 총 30대), 1기가 무료 인터넷, 추적식 욕조, IH 2구, WIC 등 상급 설비 사양 확정",
      "열화대책등급 3급 상당 증명서 보유로 목조임에도 최장 30년 융자 추진 가능하며, 30년 융자 시 채무상환년수 23.7~23.9년 및 세무평가 LTV 158~177%로 법인 재무제표 건전성 개선"
    ],
    "risks_ko": [
      "오카다부동산(임대부·대주) 공식 모집도면 및 확정 렌트롤 대조 결과, 2~3층 2LDK 전 6세대가 매매 마이소쿠 대비 일괄 월 -20,000엔 인하(17.5만~18.0만 엔+관리비 4천 엔)되어 확정 만실 연수입이 2,176.8만 엔(표면 6.60%, 매매 마이소쿠 2,386.8만 엔[7.23%] 대비 연 -210.0만 엔 감소 / 임대료만 합산 시 2,119.2만 엔·표면 6.42%[-267.6만 엔 감소])으로 하락 확정",
      "북측 4.0m 도로에 약 3.0m만 접한 노지상부지(깃대형)로 도쿄도 건축안전조례를 충족하기 위해 2·3층 세대(201~206호)를 『1층 현관 + 내부 전용계단 2개소(1F→2F→3F) 겹침나가야·메조네트』로 설계함에 따라 계단실 면적 로스(약 12~15㎡)가 발생하며, 실제 임대 모집도면에서는 2~3층 전유면적(㎡)이 『미기재(記載なし)』로 모집 중",
      "모집도면상 『거래태양: 대주(오카다부동산)』 및 객부 인센티브 『AD 100% + FR 1개월(전용 가능, 전 12호 약 353만~388만 엔)』, 그리고 『프로판가스(LP가스)』가 채택되어 있어, 2.90억~2.95억 엔 네고 + 만실 인도(AD/FR 매도자 부담) + LP가스 부외부채 부존재 특약이 필수임"
    ],
    "positives_ja": [
      "東武スカイツリーライン（日比谷線直通・始発多数）『竹ノ塚』駅西口 徒歩3分 — 2022年高架化完了＆2024年5月『EQUiA竹ノ塚』開業により駅前利便性が大幅向上",
      "近隣商業地域（80%/基準240%）の土地384.62㎡（116.35坪）＋新築延床605.17㎡（183.06坪）により、路地状補正（▲15%）後でも標準銀行積算約2億5,000万円（売出比75.8%・指値2.95億比84.7%）の高い担保力を確保",
      "岡田不動産（賃貸部）募集図面（全7枚）により、全室エアコン完備（1階各2台・2〜3階各3台、計30台）、1ギガ無料ネット、追焚機能、IHコンロ、WIC等の充実仕様が確定",
      "劣化対策等級3級相当証明書により木造ながら最長30年融資が視野に入り、30年融資時は債務償還年数23.7〜23.9年・税務LTV 158〜177%と法人決算書の健全性を大きく改善"
    ],
    "risks_ja": [
      "岡田不動産（賃貸部・貸主）の公式募集図面および確定レントロールにより、2〜3階2LDK全6戸が売買マイソク比で一律月▲20,000円引き下げ（17.5万〜18.0万円＋管理費4千円）て募集されていることが確定し、満室想定年収は2,176.8万円（表面6.60%、売買マイソク2,386.8万円［7.23%］比で年▲210.0万円減 ／ 賃料のみでは年2,119.2万円・表面6.42%［年▲267.6万円減］）へ低下",
      "北側4.0m道路に約3.0m接道の路地状敷地であり、東京都建築安全条例対応の『1階専用玄関＋内階段2ヶ所（1F→2F→3F）重ね長屋・メゾネット』構造のため階段ロス（約12〜15㎡）が生じ、実際の賃貸募集図面では2〜3階の専有面積が「記載なし」で募集されている",
      "募集図面にて『取引態様：貸主（岡田不動産）』『AD100%＋FR1ヶ月（転用可、全12戸で約353万〜388万円）』『プロパンガス（LPガス）』が判明しており、2.90億〜2.95億円への指値交渉＋満室引渡（初期AD/FR売主負担）＋LPガス無償貸与債務不存在特約が必須条件"
    ]
  },
  "top5_action_items": [
    "건축확인필증 또는 대장기재사항증명서 사본 요청",
    "준공검사필증(検査済証) 교부 유무 및 번호 확인 (은행융자 필수)",
    "현재 위탁 중인 PM 관리수수료율 및 정기청소비 월액 확인",
    "최신 연도 고정자산세·도시계획세 과세명세서(토지 평가액) 사본 요청",
    "최신 연도 고정자산세·도시계획세 과세명세서(건물 평가액) 사본 요청"
  ],
  "chapters": [
    {
      "chapter_no": 1,
      "title_ko": "1. 투자 총괄 요약 및 핵심 의사결정 권고 (Executive Summary & Verdict)",
      "title_ja": "1. エグゼクティブ・サマリーおよび投資判定 (Executive Summary & Verdict)",
      "content_ko": "**니시타케노츠카 2초메 카렌 레지던스(西竹の塚2丁目 カレンレジデンス)**는 도부 스카이트리 라인 『타케노츠카』역 도보 3분 근린상업지역 토지 384.62㎡(116.35평) 위에 신축된 **목조 3층 건 12세대(1층: 1LDK×5호+1DK×1호[197.39㎡], 2~3층: 2LDK 메조네트×6호, 연면적 605.17㎡)** 대형 아파트를 대상으로 합니다.\n\n- **오카다부동산(임대부·대주) 모집도면 7매 및 확정 렌트롤 대조 적발**: 매매 마이소쿠 헤드라인(연 2,386.8만 엔 / 7.23%) 및 표 합산(연 2,320.8만 엔 / 7.03%)과 달리, 실제 임대 모집도면에서는 **2~3층 2LDK 6세대 전 호실이 일괄 월 -20,000엔 인하(17.5만~18.0만 엔+관리비 4,000엔)**되어 **확정 만실 연수입(GPI)은 관리비 포함 2,176.8만 엔(표면 6.60%, 연 -210.0만 엔 감소 / 실효 NOI 1,701.1만 엔 [Cap 5.15%]), 임대료만 합산 시 2,119.2만 엔(표면 6.42%, 연 -267.6만 엔 감소)**으로 확정되었습니다.\n- **최종 판정**: **조건부 매수(Conditional Buy, 61/100점 | 19.6/30점, C+ 등급)** — 호가 3.30억 엔 매수는 보류하며, **2억 9,000만~2억 9,500만 엔(모집확정 기준 표면 7.38%~7.51%) 지가 네고 + 30년 융자 특약 + 만실 인도(AD100%+FR1개월 매도자 부담) 특약** 성사 시에만 매수를 권고합니다.",
      "content_ja": "**西竹の塚2丁目 カレンレジデンス**は、東武スカイツリーライン『竹ノ塚』駅徒歩3分の近隣商業地域（土地384.62㎡・116.35坪）に新築された**木造3階建・全12戸（1階：1LDK×5戸＋1DK×1戸［計197.39㎡］、2〜3階：2LDKメゾネット×6戸、延床605.17㎡）**の一棟アパートです。\n\n- **岡田不動産（賃貸部・貸主）募集図面（全7枚）および確定レントロール監査**: 売買マイソク表面記載（年2,386.8万円 / 7.23%）および表合算（年2,320.8万円 / 7.03%）に対し、実際の賃貸募集図面では**2〜3階2LDK全6戸が一律月▲20,000円引き下げ（17.5万〜18.0万円＋管理費4,000円）**て募集されており、**確定満室GPIは管理費込みで年2,176.8万円（表面6.60%・年▲210.0万円減 ／ 実効NOI 1,701.1万円［Cap 5.15%］）、賃料のみでは年2,119.2万円（表面6.42%・年▲267.6万円減）**となることが確定しました。\n- **最終判定**: **条件付推奨（Conditional Buy、61/100点｜19.6/30点、ランクC+）** — 売出3.30億円での買付は見送り、**2億9,000万〜2億9,500万円（募集図面確定ベース表面7.38%〜7.51%）への指値交渉＋30年融資特約＋満室引渡（初期AD100%＋FR1ヶ月売主負担）特約**を必須条件とします。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 2,
      "title_ko": "2. 물건 개요 및 누락 정보 감사 (Property Overview & Missing Info Audit)",
      "title_ja": "2. 物件概要および未開示情報の監査 (Property Overview & Missing Info Audit)",
      "content_ko": "- **토지 및 접도 리스크**: 아다치구 니시타케노츠카 2초메 1325-29(주거표시 2-4-36), 토지 384.62㎡(근린상업지역, 건폐율 80%/기준용적률 240%), **북측 4.0m 공도에 약 3.0m만 접한 노지상부지(깃대형)**.\n- **건물 및 설비 리스크**: 목조 3층 건 연면적 605.17㎡, 2026년 8~10월 신축(시공사: 하우스링크홈(주)), 열화등급 3급 상당 증명서 유. 단, **도쿄 23구 역세권임에도 시공사 그룹 가스공급 구조에 따라 LP가스(프로판가스)가 채택**되어 있어 무상대여 설비 잔존 채무 유무 및 3부 요금제 내역서 징구가 필수입니다.",
      "content_ja": "- **土地および接道リスク**: 足立区西竹の塚二丁目1325-29（住居表示2-4-36）、土地384.62㎡（近隣商業地域、建蔽率80%/基準容積率240%）、**北側4.0m公道に約3.0mのみ接面する路地状敷地（旗竿地）**。\n- **建物および設備リスク**: 木造3階建・延床605.17㎡、2026年8〜10月新築（施工：ハウスリンクホーム(株)）、劣化等級3級相当証明書有。ただし**東京23区駅近でありながらLPガス（プロパンガス）が採用**されており、無償貸与設備の残存債務有無および三部料金制明細の徴求が必須です。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 3,
      "title_ko": "3. 입지·상권 및 도쿄 4대 거점 통근 접근성 검증 (Location & Transit Access)",
      "title_ja": "3. 立地・商圏および主要4大拠点への通勤アクセス検証 (Location & Transit Access)",
      "content_ko": "- **타케노츠카역 고가화(2022.3) 및 『EQUiA 타케노츠카』(2024.5) 개업 효과**: 장기간 지역 단절을 유발하던 건널목이 고가화로 완전 해소되었고 역사 내 24개 점포가 입점한 에키아 타케노츠카 및 서구 도보 2분 24시간 세이유(SEIYU)로 생활 편의성이 뛰어납니다.\n- **도심 직통 접근성**: 도쿄메트로 히비야선 직통(당역 시발 다수)으로 **우에노역 20분(환승 0회), 아키하바라역 25분(0회), 오테마치역 33분(키타센주 1회 환승), 긴자역 37분(0회)**에 주파합니다.",
      "content_ja": "- **竹ノ塚駅高架化（2022.3）および『EQUiA竹ノ塚』（2024.5）開業効果**: 開かずの踏切が完全解消され、高架下商業施設エキア竹ノ塚（24店舗）および西口徒歩2分の24時間営業「西友（SEIYU）」により高い生活利便性を誇ります。\n- **都心直通アクセス**: 東京メトロ日比谷線直通（当駅始発多数）により**上野駅20分（乗換0回）、秋葉原駅25分（0回）、大手町駅33分（北千住1回乗換）、銀座駅37分（0回）**でアクセス可能です。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 4,
      "title_ko": "4. 적산평가(원가법) 및 토지·건물 담보가치 정밀 검증 (Reproduction Cost Valuation)",
      "title_ja": "4. 積算評価（原価法）および土地・建物担保価値の精密査定 (Reproduction Cost Valuation)",
      "content_ko": "- **토지 적산평가**: 인근 근린상업 기준지가(67.5만 엔/㎡) 및 주택지 공시지가(40.3만 엔/㎡)를 바탕으로 본건 전면 상속세 노선가를 `450,000엔/㎡`로 추계하고, **노지상부지(접도 3.0m) 감가 보정(-15%)을 적용한 실효 단가 `382,500엔/㎡` × 384.62㎡ = 1억 4,711.7만 엔**(무보정 시 1억 7,307.9만 엔).\n- **건물 및 합산 적산평가(연면적 605.17㎡, 잔존 22/22년)**:\n  1. **은행 보수 기준(15만 엔/㎡)**: 건물 9,077.6만 + 토지 1억 4,711.7만 = **2억 3,789.3만 엔 (72.1%)**\n  2. **표준 은행 담보 기준(17만 엔/㎡)**: 건물 1억 287.9만 + 토지 1억 4,711.7만 = **2억 4,999.6만 엔 (75.8% / 네고가 2.95억 대비 84.7%)**\n  3. **국세청·무보정 노선가 기준(18만 엔/㎡)**: 건물 1억 893.1만 + 토지 1억 7,307.9만 = **2억 8,201.0만 엔 (85.5%)**",
      "content_ja": "- **土地積算評価**: 近隣商業基準地価（67.5万円/㎡）等を基に前面路線価を`450,000円/㎡`と推計し、**路地状敷地（接道3.0m）補正（▲15%）適用後の実効単価 `382,500円/㎡` × 384.62㎡ ＝ 1億4,711.7万円**（無補正時 1億7,307.9万円）。\n- **建物および合算積算評価（延床605.17㎡、残存22/22年）**:\n  1. **銀行保守基準（15万円/㎡）**: 建物9,077.6万＋土地1億4,711.7万 ＝ **2億3,789.3万円（72.1%）**\n  2. **標準銀行担保基準（17万円/㎡）**: 建物1億287.9万＋土地1億4,711.7万 ＝ **2億4,999.6万円（75.8% ／ 指値2.95億比 84.7%）**\n  3. **国税庁・無補正路線価基準（18万円/㎡）**: 建物1億893.1万＋土地1億7,307.9万 ＝ **2億8,201.0万円（85.5%）**",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 5,
      "title_ko": "5. 렌트롤 3단계 포렌식 감사 및 평면(메조네트 계단로스) 경쟁력 분석",
      "title_ja": "5. レントロール3段階フォレンジック監査および間取り（階段ロス）競争力分析",
      "content_ko": "- **오카다부동산(임대부) 모집도면 7매 정밀 대조**: 1층 `106호`가 매매 마이소쿠(1LDK)와 달리 **1DK(DK 약7첩+양실 약5첩)**로 확정되었고, 2~3층 메조네트(`201~206호`)는 계단실 로스(약 12~15㎡)로 인해 임대 모집도면에 **전유면적 『미기재(記載なし)』**로 등록되어 있으며 평면은 ①`201~204호`(2F LDK 12.2첩 / 3F 양실 2개+WIC 2개), ②`205호`(2F 양실 2개+욕실 / **3F 대형 LDK 18.1첩**), ③`206호`(2F LDK 14.1첩 / 3F 양실 2개+욕실)의 3타입으로 구성됩니다.\n- **4단계 수입 비교**: ①매매 마이소쿠 헤드라인 **연 2,386.8만 엔(7.23%)** vs ②매매 마이소쿠 표 합산 **연 2,320.8만 엔(7.03%)** vs ③**오카다부동산 모집도면 확정(관리비 포함) 연 2,176.8만 엔(6.60%, 월 181.4만 엔)** vs ④**모집도면 확정(임대료만) 연 2,119.2만 엔(6.42%, 월 176.6만 엔)**.\n- **초기 모집 조건**: 예금 1개월 + 멘테넌스 비용 1개월(퇴거 시 전액 상각) + 조기해약 위약금(1년 미만 1개월, 2년 미만 0.5개월) 및 객부 중개사 인센티브 **`AD 100% + FR 1개월(전용 가능)`** 설정.",
      "content_ja": "- **岡田不動産（賃貸部）募集図面（全7枚）の精密照合**: 1階`106号室`が売買マイソク（1LDK）と異なり**1DK（DK約7帖＋洋室約5帖）**で確定。2〜3階メゾネット（`201〜206号室`）は階段ロス（約12〜15㎡）を考慮して賃貸募集図面では**専有面積「記載なし」**となっており、間取りは①`201〜204号室`（2F LDK12.2帖／3F 洋室2室＋WIC2ヶ所）、②`205号室`（2F 洋室2室＋水回り／**3F 大型LDK18.1帖**）、③`206号室`（2F LDK14.1帖／3F 洋室2室＋水回り）の3タイプで構成されています。\n- **4段階収入比較**: ①売買マイソク表面 **年2,386.8万円（7.23%）** vs ②売買マイソク表合算 **年2,320.8万円（7.03%）** vs ③**岡田不動産 募集図面確定［管理費込］年2,176.8万円（6.60%・月181.4万円）** vs ④**募集図面確定［賃料のみ］年2,119.2万円（6.42%・月176.6万円）**。\n- **募集・契約条件**: 礼金1ヶ月＋メンテナンス費用1ヶ月（退去時全額償却）＋早期解約違約金（1年未満1ヶ月・2年未満0.5ヶ月）および客付インセンティブ**『AD100%＋FR1ヶ月（転用可）』**。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 6,
      "title_ko": "6. 운영경비(OPEX) 정규화 및 순영업소득(NOI) 모델링",
      "title_ja": "6. 運営経費(OPEX)の正規化および純営業収益(NOI)モデリング",
      "content_ko": "- **정규화 연간 운영경비(OPEX) ¥3,663,600 (포털 실세 GPI 대비 16.90% / 명목 GPI 대비 ¥3,773,400 [15.81%])**:\n  1. PM 위탁수수료(5.0%): **¥1,083,600**\n  2. 공용부 전기·수도·정기청소·전 12호 무료 인터넷 ISP: **¥540,000**\n  3. 고정자산세·도시계획세(소규모주택용지 1/6·1/3 특례 반영 평준화): **¥1,320,000**\n  4. 화재·지진보험(연환산): **¥180,000**\n  5. 퇴거 원상복구·AD 충당금(¥240,000) + 장기수선적립금(¥300,000): **¥540,000**\n- **실효 순영업소득(Effective NOI, 공실 5% 차감)**: 포털 실세 기준 **¥16,924,800 (Cap Rate 5.13% / 네고가 2.95억 기준 5.74%)**, 명목 기준 **¥18,901,200 (Cap Rate 5.73%)**.",
      "content_ja": "- **正規化年間運営経費(OPEX) ¥3,663,600（ポータル実勢GPI比 16.90% ／ 表面GPI比 ¥3,773,400［15.81%］）**:\n  1. PM管理委託費（5.0%）: **¥1,083,600**\n  2. 共用光熱費・定期清掃・全12戸無料ネットISP: **¥540,000**\n  3. 固定資産税・都市計画税（小規模住宅用地1/6・1/3特例反映平準化）: **¥1,320,000**\n  4. 火災・地震保険料（年換算）: **¥180,000**\n  5. 原状回復・募集AD引当（¥240,000）＋長期修繕積立（¥300,000）: **¥540,000**\n- **実効営業純利益(Effective NOI、空室5%控除)**: ポータル実勢基準 **¥16,924,800（Cap Rate 5.13% ／ 指値2.95億基準 5.74%）**、表面基準 **¥18,901,200（Cap Rate 5.73%）**。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 7,
      "title_ko": "7. 금융 조달, 현금흐름(Cash Flow) 및 법인 결산서 착지 분석",
      "title_ja": "7. 融資ストラクチャー・キャッシュフローおよび法人決算書着地分析",
      "content_ko": "- **30년 융자(열화3급) vs 22년 융자(법정 내용연수) 스트레스 비교 (포털 실세 GPI 2,167.2만 엔 기준)**:\n  1. **호가 3.30억 / 30년 / 2.2%**: 연간 원리금(ADS) ¥12,028,923 → **세전 CF +¥4,895,877, 세후 CF +¥3,283,663 (DSCR 1.41배, 상환연수 27.5년)**\n  2. **호가 3.30억 / 22년(법정연수 제한 시) / 2.2%**: ADS ¥15,148,131 → **세전 CF +¥1,776,669, 세후 CF +¥156,543 (0.05%, 법인세 162만 엔 납부 후 현금 완전 고갈!)**\n  3. **목표 네고가 2.95억 / 30년 / 2.2% [권고]**: 대출 ¥236,000,000, ADS ¥10,753,128 → **세전 CF +¥6,171,672, 세후 CF +¥4,281,686 (DSCR 1.57배, 상환연수 22.9년, 세무 LTV 157.9%)**",
      "content_ja": "- **30年融資（劣化3級）vs 22年融資（法定耐用年数）ストレス比較（ポータル実勢GPI 2,167.2万円基準）**:\n  1. **売出3.30億 / 30年 / 2.2%**: 年間元利返済（ADS）¥12,028,923 → **税引前CF +¥4,895,877、税引後CF +¥3,283,663（DSCR 1.41倍・償還年数27.5年）**\n  2. **売出3.30億 / 22年（法定制限時）/ 2.2%**: ADS ¥15,148,131 → **税引前CF +¥1,776,669、税引後CF +¥156,543（0.05%・法人税162万円控除後に手残り枯渇！）**\n  3. **目標指値 2.95億 / 30年 / 2.2%［推奨］**: 借入 ¥236,000,000、ADS ¥10,753,128 → **税引前CF +¥6,171,672、税引後CF +¥4,281,686（DSCR 1.57倍・償還年数22.9年・税務LTV 157.9%）**",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 8,
      "title_ko": "8. 가격 협상(Price Negotiation) 및 10년 보유 출구(Exit) 시뮬레이션",
      "title_ja": "8. 指値交渉シナリオおよび10年保有イグジット（Exit）試算",
      "content_ko": "- **23년차 감가상각 소멸 절벽 대비 10~15년차 매각(Exit) 전략**: 목조 법정 상각기간(22년)이 끝나는 23년차부터 연간 약 473만 엔의 감가상각비가 소멸하므로, 잔존 내용연수가 남아 있는 **10~15년차 매각**이 최적입니다.\n- **10년 보유 후 매각(축 10년 Exit 표면 7.5% = 예상 매각가 2억 7,480만 엔 기준)**:\n  - 호가(3.30억 엔) 매입 시: 초기 자기자본 9,122만 엔 대비 **10년 총 순이익 +1,008만 엔 (연환산 ROI +1.1%)**에 불과.\n  - **목표 네고가(2.95억 엔) 매입 시**: 10년 누적 세후 CF +4,015만 엔 + 매각 순회수금 9,177만 엔 − 초기 자기자본 8,239만 엔 = **10년 총 순이익 +4,953만 엔 (자기자본배수 1.60배, 연환산 ROI +6.0%)**.",
      "content_ja": "- **23年目の減価償却消滅の崖を見据えた10〜15年目イグジット戦略**: 木造法定耐用年数（22年）満了後の23年目から減価償却費（年約473万円）がゼロとなるため、**築10〜15年目での売却（Exit）**が最適です。\n- **10年保有後イグジット試算（築10年Exit表面7.5%＝想定売却額2億7,480万円基準）**:\n  - 売出価格（3.30億円）購入時: 初期自己資金9,122万円に対し **10年総純利益 +1,008万円（年換算ROI +1.1%）**と低조。\n  - **目標指値（2.95億円）購入時**: 10年累積税引後CF +4,015万円 ＋ 売却手残り9,177万円 − 自己資金8,239万円 ＝ **10年総純利益 +4,953万円（自己資金倍率 1.60倍、年換算ROI +6.0%）**。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 9,
      "title_ko": "9. 재해(아라카와 홍수 해저드맵), 건축안전조례, LP가스 및 금리 스트레스 테스트",
      "title_ja": "9. ハザード（荒川浸水想定）・建築安全条例・LPガスおよび金利ストレステスト",
      "content_ko": "- **아다치구 홍수 해저드맵**: 아라카와 범람 시 예상 침수심 **0.5m~3.0m 미만 구역(1층 침수 가능)**에 해당하여 화재보험 가입 시 **수재(水災) 보상 특약**이 필수입니다.\n- **도쿄도 건축안전조례(접도 3.0m)**: 연면적 605.17㎡(>500㎡)·접도 3.0m 조건으로 인해 건축확인상 용도가 『나가야(長屋)』로 허가되었을 가능성이 높으므로 확인필증·검사필증 확인이 필수입니다.\n- **복합 스트레스 테스트(금리 3.0% + 가동률 85%[2실 공실])**: 호가 3.30억 매입 시 **세후 CF -52.0만 엔 적자**로 전락하는 반면, **네고가 2.95억 매입 시 세후 CF +65.4만 엔(DSCR 1.12배) 흑자를 방어**합니다.",
      "content_ja": "- **足立区洪水ハザードマップ**: 荒川氾濫時の想定浸水深 **0.5m〜3.0m未満区域（1階床上浸水相当）**に該当するため、火災保険での**水災補償特約付帯**が必須です。\n- **東京都建築安全条例（接道3.0m）**: 延床605.17㎡（500㎡超）・接道3.0mのため建築確認上の用途が『長屋』である可能性が高く、確認済証・検査済証での用途確認が不可欠です。\n- **複合ストレステスト（金利3.0%＋稼働率85%［2室空室］）**: 売出3.30億円では**税引後CF ▲52.0万円の赤字**に転落する一方、**指値2.95億円なら税引後CF +65.4万円（DSCR 1.12倍）の黒字を防衛**します。",
      "slug": "karen-residence-nishitakenotsuka"
    },
    {
      "chapter_no": 10,
      "title_ko": "10. 종합 의사결정 스코어카드 및 매수(LOI)·실사(DD) 실행 가이드",
      "title_ja": "10. 総合意思決定スコアカードおよび買付(LOI)・DD実行ガイド",
      "content_ko": "- **종합 스코어카드**: **61 / 100점 (19.6 / 30점, C+ 등급: 조건부 매수 Conditional Buy)**\n- **매수의향서(LOI) 제시 조건**: 목표 매수가 **2억 9,000만~2억 9,500만 엔(포털 실세 기준 표면 7.35%~7.47%)**\n- **매매계약 필수 4대 특약**:\n  1. **융자 특약**: 열화등급 3급 증명서 기반 **대출 2.36억 엔(LTV 80%) 이상·융자기간 30년 이상·금리 2.25% 이하** 승인 조건.\n  2. **만실 인도 또는 12개월 서브리스 보증 특약**: 잔금 시 최소 10세대 이상 실입주 완료 또는 12개월간 포털 실세 월세 보증(초기 AD 매도자 부담).\n  3. **LP가스 무상대여 부외부채 부존재 보증 특약**: 급탕기·에어컨·배관 등에 승계 채무·위약금 일절 없음 보증.\n  4. **준공검사필증 및 열화대책등급 3급 증명서 정본 인도 특약**.",
      "content_ja": "- **総合スコアカード**: **61 / 100点（19.6 / 30点、ランクC+：条件付推奨 Conditional Buy）**\n- **買付申込書（LOI）提示条件**: 指値目標 **2億9,000万〜2億9,500万円（ポータル実勢表面 7.35%〜7.47%）**\n- **売買契約必須4大特約**:\n  1. **融資特約**: 劣化等級3級証明書に基づく**借入2.36億円（LTV 80%）以上・融資期間30年以上・金利2.25%以下**の承認条件。\n  2. **満室引渡または12ヶ月間サブリース保証特約**: 決済時最低10戸以上成約または12ヶ月間の実勢家賃保証（初期AD売主負担）。\n  3. **LPガス無償貸与債務不存在保証特約**: 給湯器・エアコン・配管等の貸与残存債務・違約金が一切無いことの売主保証。\n  4. **検査済証および劣化対策等級3級証明書原本の引渡特約**。",
      "slug": "karen-residence-nishitakenotsuka"
    }
  ]
};
