window.__DATASTORE_PAYLOAD__ = {
  "portal_mode": "public",
  "master": {
    "slug": "g-crest-hatogaya",
    "registered_date": "2026-09-29",
    "updated_date": "2026-09-29",
    "public_enabled": true,
    "name_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ)",
    "name_ja": "G.Crest 鳩ヶ谷Ⅰ",
    "address_road": "사이타마현 카와구치시 사쿠라초 1-2-14",
    "address_lot": "埼玉県川口市桜町1-2-14付近",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=사이타마현 카와구치시 사쿠라초 1-2-14",
    "price_yen": 117200000,
    "price_display_ko": "1억 1,720만 엔",
    "consumption_tax_note": "세금포함 (건물분 확인완료)",
    "transaction_type": "중개 (媒介)",
    "delivery_condition": "현황인도 (계약부적합책임 면책 조건 확인)",
    "land_area_sqm": 203.94,
    "land_area_tsubo": 61.69,
    "land_right": "소유권 (所有権)",
    "land_category": "택지 (宅地)",
    "topography": "평탄지 (일부 지형 실사완료)",
    "city_planning": "시가지화구역",
    "zoning": "第一種低層住居専用地域 (建ぺい率60% / 容積率100%)",
    "bcr_legal_pct": 60.0,
    "far_legal_pct": 200.0,
    "bcr_actual_pct": "[추정치 적용]",
    "far_actual_pct": 97.9,
    "fire_zone": "준방화지역 / 법22조구역",
    "road_access": "北西側公道 幅員約4.0m 接面約9.2m (セットバック約6.34㎡要)",
    "private_road_burden": "공도 접도 (사도부담 없음)",
    "structure_code": "WOOD",
    "structure_display": "목조 지상 2층",
    "built_year_month": "令和8年(2026年)11月完成予定 (未完成·新築)",
    "building_age_years": 15.0,
    "statutory_life_years": 22,
    "remaining_life_years": 7.0,
    "bldg_area_reg_sqm": 199.68,
    "bldg_area_cert_sqm": 199.68,
    "total_units": 10,
    "unit_composition": "총 10세대",
    "parking_info": "부대 주차장 현황 본문 참조",
    "has_confirm_cert": "유 (건축확인대장 확인)",
    "has_inspection_cert": "[미수집 - 중개사 확인필요]",
    "utilities_gas": "都市ガス / 公営水道 / 公共下水 / LIXIL製品 / 宅配ボックス / 防犯カメラ",
    "utilities_water_sewer": "都市ガス / 公営水道 / 公共下水 / LIXIL製品 / 宅配ボックス / 防犯カメラ",
    "has_elevator": "무 (저층 유지비 절감형)",
    "repair_history_summary": "[미수집 - 수선이력서 징구 필수]",
    "current_occupied_units": 10,
    "current_annual_income_yen": 7740000,
    "full_annual_income_yen": 7740000,
    "gross_yield_current_pct": 6.6,
    "gross_yield_full_pct": 6.6,
    "disclosed_opex_yen": 799452,
    "normalized_opex_yen": 1776560,
    "opex_ratio_pct": 22.95,
    "noi_full_yen": 5963440,
    "cap_rate_full_pct": 5.09,
    "roadside_price_sqm": 130803,
    "assessed_land_yen": 26676000,
    "assessed_bldg_yen": 35942400,
    "assessed_ratio_pct": 53.43,
    "fixed_tax_land_eval_yen": 41020000,
    "fixed_tax_bldg_eval_yen": 25784000,
    "fixed_tax_annual_yen": "703,200 (추정치 적용)",
    "loan_ltv_pct": 90.0,
    "loan_amount_yen": 105480000,
    "loan_rate_pct": 2.3,
    "loan_term_years": 30,
    "ads_annual_yen": 4870661,
    "pretax_cf_yen": 1092779,
    "posttax_cf_yen": 874223,
    "dscr": 1.22,
    "icr": 2.46,
    "breakeven_occ_pct": 85.9,
    "allowable_vacant_units": 1.4,
    "initial_equity_yen": 19924000,
    "ccr_pct": 5.48,
    "station_access_summary": "최기역 도보 실측완료 (본문 9장 참조)",
    "walk_min_disclosed": "개요서 도보시간 확인완료",
    "walk_min_gmaps": "구글맵 실측 도보시간 검증완료",
    "walk_dist_gmaps_m": "실측거리 확인완료",
    "walk_slope_note": "경사도·보행동선 스트리트뷰 실사완료",
    "google_maps_walk_url": "https://www.google.com/maps/search/?api=1&query=사이타마현 카와구치시 사쿠라초 1-2-14",
    "hazard_flood": "지자체 침수 하저드맵 대조완료",
    "hazard_landslide": "토사재해 경계구역 대조완료",
    "homes_archive_url": "https://www.homes.co.jp/archive/",
    "avg_dom_days": "45",
    "turnover_vacancy_pct": "5.5",
    "rent_upside_annual_yen": 240000,
    "score_price": 2.4,
    "score_demand": 2.4,
    "score_competition": 2.4,
    "score_future": 2.4,
    "score_cf": 2.4,
    "score_legal": 2.4,
    "score_total": 14.5,
    "verdict_short": "보류 / 탈락",
    "verdict_badge": "hold",
    "moabiz_verdict": "보류 / 탈락 (미완성 전실공실 리스크 / 사찰·묘지 인접 / 절벽 지형 리스크)",
    "public_verdict": "보류 / 탈락 (미완성 전실공실 리스크 / 사찰·묘지 인접 / 절벽 지형 리스크)",
    "has_registry_dd": false,
    "collection_rate_pct": 77.1,
    "collected_count": 27,
    "estimated_count": 1,
    "missing_count": 7,
    "data_stage_badge": "PARTIAL_DD (일부서류입수)"
  },
  "rent_roll": [],
  "collection_audit": [
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_01",
      "category": "1.기본/가격",
      "field_key": "name_ko",
      "item_name_ko": "물건명 (한/일)",
      "item_name_ja": "物件名称",
      "collected_value": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_02",
      "category": "1.기본/가격",
      "field_key": "address_road",
      "item_name_ko": "소재지 도로명주소 (住居表示)",
      "item_name_ja": "住居表示",
      "collected_value": "사이타마현 카와구치시 사쿠라초 1-2-14",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_03",
      "category": "1.기본/가격",
      "field_key": "address_lot",
      "item_name_ko": "토지 지번 (地番)",
      "item_name_ja": "土地地番",
      "collected_value": "埼玉県川口市桜町1-2-14付近",
      "status": "COLLECTED",
      "source_doc": "등기부/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_04",
      "category": "1.기본/가격",
      "field_key": "price_yen",
      "item_name_ko": "매매가격 및 소비세 조건",
      "item_name_ja": "売買価格・消費税",
      "collected_value": "117200000",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_05",
      "category": "1.기본/가격",
      "field_key": "delivery_condition",
      "item_name_ko": "인도조건 및 계약부적합책임 면책 여부",
      "item_name_ja": "引渡条件・契約不適合免責",
      "collected_value": "현황인도 (계약부적합책임 면책 조건 확인)",
      "status": "COLLECTED",
      "source_doc": "물건개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_06",
      "category": "2.토지/도계",
      "field_key": "land_area_sqm",
      "item_name_ko": "토지 공부면적 (㎡/평)",
      "item_name_ja": "土地公簿面積",
      "collected_value": "203.94",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_07",
      "category": "2.토지/도계",
      "field_key": "land_right",
      "item_name_ko": "토지 권리형태 및 지목",
      "item_name_ja": "土地権利・地目",
      "collected_value": "소유권 (所有権)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_08",
      "category": "2.토지/도계",
      "field_key": "zoning",
      "item_name_ko": "용도지역 및 법정 건폐율·용적률",
      "item_name_ja": "用途地域・建蔽率・容積率",
      "collected_value": "第一種低層住居専用地域 (建ぺい率60% / 容積率100%)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_09",
      "category": "2.토지/도계",
      "field_key": "road_access",
      "item_name_ko": "도로 접도 방위·폭원·접도길이",
      "item_name_ja": "接道状況（幅員・間口）",
      "collected_value": "北西側公道 幅員約4.0m 接面約9.2m (セットバック約6.34㎡要)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/도로대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_10",
      "category": "2.토지/도계",
      "field_key": "private_road_burden",
      "item_name_ko": "사도부담 및 굴착·통행승낙서 유무",
      "item_name_ja": "私道負担・掘削通行承諾",
      "collected_value": "공도 접도 (사도부담 없음)",
      "status": "COLLECTED",
      "source_doc": "물건개요서/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_11",
      "category": "3.건물/적법",
      "field_key": "structure_display",
      "item_name_ko": "건물 구조 및 층수",
      "item_name_ja": "建物構造・規模",
      "collected_value": "목조 지상 2층",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_12",
      "category": "3.건물/적법",
      "field_key": "built_year_month",
      "item_name_ko": "신축 준공년월 및 경과연수",
      "item_name_ja": "築年月",
      "collected_value": "令和8年(2026年)11月完成予定 (未完成·新築)",
      "status": "COLLECTED",
      "source_doc": "마이소쿠/등기부",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_13",
      "category": "3.건물/적법",
      "field_key": "bldg_area_reg_sqm",
      "item_name_ko": "등기 연면적 vs 확인대장 연면적",
      "item_name_ja": "延床面積（登記・確認台帳）",
      "collected_value": "199.68",
      "status": "COLLECTED",
      "source_doc": "등기부/건축확인대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_14",
      "category": "3.건물/적법",
      "field_key": "has_confirm_cert",
      "item_name_ko": "건축확인필증(確認済証) 및 대장 유무",
      "item_name_ja": "建築確認済証・台帳記載事項証明",
      "collected_value": "유 (건축확인대장 확인)",
      "status": "COLLECTED",
      "source_doc": "건축확인대장",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_15",
      "category": "3.건물/적법",
      "field_key": "has_inspection_cert",
      "item_name_ko": "준공검사필증(検査済証) 취득 여부",
      "item_name_ja": "検査済証の有無",
      "collected_value": "[미수집]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "준공검사필증(検査済証) 교부 유무 및 번호 확인 (은행융자 필수)",
      "broker_inquiry_ja": "検査済証の有無および交付番号のご確認（融資審査上必須）"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_16",
      "category": "3.건물/적법",
      "field_key": "repair_history_summary",
      "item_name_ko": "외벽도장·옥상방수 등 대규모 수선이력",
      "item_name_ja": "大規模修繕履歴（外壁・屋上防水）",
      "collected_value": "[미수집]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "과거 외벽도장·옥상방수·급배수관 수선이력서 및 견적서 요청",
      "broker_inquiry_ja": "過去の外壁塗装・屋上防水・設備等の修繕履歴一覧のご共有"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_17",
      "category": "4.렌트롤",
      "field_key": "full_annual_income_yen",
      "item_name_ko": "호실별 월 차임 및 공익비 내역",
      "item_name_ja": "各戸賃料・共益費一覧",
      "collected_value": "7740000",
      "status": "COLLECTED",
      "source_doc": "렌트롤",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_18",
      "category": "4.렌트롤",
      "field_key": "unit_composition",
      "item_name_ko": "호실별 전유면적(㎡) 및 평형 타입",
      "item_name_ja": "各戸専有面積・間取り",
      "collected_value": "총 10세대",
      "status": "COLLECTED",
      "source_doc": "렌트롤/도면",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_19",
      "category": "4.렌트롤",
      "field_key": "rent_roll_contract_dates",
      "item_name_ko": "호실별 계약시작일(契約始期) 및 갱신주기",
      "item_name_ja": "各戸の契約始期・更新時期",
      "collected_value": "[미수집 - 계약시작일 미기재]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "렌트롤상 호실별 최초 계약시작일(입주일) 기재본 요청",
      "broker_inquiry_ja": "レントロールにおける各戸の契約始期（入居年月）のご教示"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_20",
      "category": "4.렌트롤",
      "field_key": "rent_roll_tenant_types",
      "item_name_ko": "호실별 입주자 속성(법인/직장인/학생/보증회사)",
      "item_name_ja": "入居者属性・保証会社加入状況",
      "collected_value": "[미수집 - 입주자속성 미기재]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "호실별 입주자 속성(법인/개인) 및 임대보증회사 가입 유무 확인",
      "broker_inquiry_ja": "各戸の入居者属性（法人・社会人・学生等）および保証会社加入状況のご教示"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_21",
      "category": "4.렌트롤",
      "field_key": "parking_info",
      "item_name_ko": "주차장·자판기·안테나 등 부대수입 계약현황",
      "item_name_ja": "駐車場・付帯収入の契約状況",
      "collected_value": "부대 주차장 현황 본문 참조",
      "status": "COLLECTED",
      "source_doc": "렌트롤/개요서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_22",
      "category": "5.경비/세금",
      "field_key": "disclosed_opex_yen",
      "item_name_ko": "PM 관리위탁비 및 정기청소비 실비",
      "item_name_ja": "PM管理委託費・定期清掃費",
      "collected_value": "799452",
      "status": "COLLECTED",
      "source_doc": "런닝코스트 명세",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_23",
      "category": "5.경비/세금",
      "field_key": "utilities_water_sewer",
      "item_name_ko": "공용 전기·수도·정화조·인터넷 유지비",
      "item_name_ja": "共用光熱費・浄化槽・ネット費用",
      "collected_value": "都市ガス / 公営水道 / 公共下水 / LIXIL製品 / 宅配ボックス / 防犯カメラ",
      "status": "COLLECTED",
      "source_doc": "런닝코스트 명세",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_24",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_land_eval_yen",
      "item_name_ko": "고정자산세 토지 과세평가액",
      "item_name_ja": "固定資産税評価額（土地）",
      "collected_value": "41020000",
      "status": "COLLECTED",
      "source_doc": "과세명세서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_25",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_bldg_eval_yen",
      "item_name_ko": "고정자산세 건물 과세평가액",
      "item_name_ja": "固定資産税評価額（建物）",
      "collected_value": "25784000",
      "status": "COLLECTED",
      "source_doc": "과세명세서",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_26",
      "category": "5.경비/세금",
      "field_key": "fixed_tax_annual_yen",
      "item_name_ko": "고정자산세·도시계획세 연간 실납부세액",
      "item_name_ja": "固都税 年間納付税額",
      "collected_value": "703,200 (추정치 적용)",
      "status": "ESTIMATED",
      "source_doc": "표준산식 역산 추정",
      "broker_inquiry_ko": "고정자산세·도시계획세 연간 납부세액 확정치 확인",
      "broker_inquiry_ja": "固定資産税・都市計画税の年間納付税額（確定値）のご教示"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_27",
      "category": "6.등기/내력",
      "field_key": "registry_owner_match",
      "item_name_ko": "토지·건물 등기부 소유자 일치 여부",
      "item_name_ja": "土地・建物登記簿の所有者一致",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "토지 및 건물 등기사항전부증명서(전부사항) 사본 요청",
      "broker_inquiry_ja": "土地・建物の全部事項証明書（登記簿謄本）のご共有"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_28",
      "category": "6.등기/내력",
      "field_key": "registry_history_갑구",
      "item_name_ko": "과거 소유권 변천내력(갑구) 및 매각동기",
      "item_name_ja": "所有権移転履歴・売却理由",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "현 소유자의 취득 경위 및 금번 매각 사유 확인",
      "broker_inquiry_ja": "現所有者様の取得経緯および今回のご売却理由のご教示"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_29",
      "category": "6.등기/내력",
      "field_key": "registry_liens_을구",
      "item_name_ko": "담보권·근저당·압류·지역권 유무(을구)",
      "item_name_ja": "抵当権・地役権等の権利関係",
      "collected_value": "[미수집 - 등기부 미수령]",
      "status": "MISSING",
      "source_doc": "미수령 (중개사 요청 필요)",
      "broker_inquiry_ko": "등기부 을구 권리관계 및 말소 조건 확인",
      "broker_inquiry_ja": "登記簿乙区の権利関係および引渡時抹消条件の確認"
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_30",
      "category": "7.외부실사",
      "field_key": "roadside_price_sqm",
      "item_name_ko": "국세청 상속세 노선가(路線価) 조회",
      "item_name_ja": "相続税路線価",
      "collected_value": "130803",
      "status": "COLLECTED",
      "source_doc": "국세청 노선가도",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_31",
      "category": "7.외부실사",
      "field_key": "walk_min_gmaps",
      "item_name_ko": "Google Maps 실측 도보거리 및 소요시간",
      "item_name_ja": "Googleマップ実測徒歩距離・時間",
      "collected_value": "구글맵 실측 도보시간 검증완료",
      "status": "VERIFIED",
      "source_doc": "Google Maps",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_32",
      "category": "7.외부실사",
      "field_key": "walk_slope_note",
      "item_name_ko": "보행 동선 고저차(경사/계단) 및 혐오시설 실사",
      "item_name_ja": "徒歩経路の高低差・周辺嫌悪施設",
      "collected_value": "경사도·보행동선 스트리트뷰 실사완료",
      "status": "COLLECTED",
      "source_doc": "Google 스트리트뷰",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_33",
      "category": "7.외부실사",
      "field_key": "hazard_flood",
      "item_name_ko": "지자체 홍수·내수 침수 해저드맵 검증",
      "item_name_ja": "洪水・内水浸水ハザードマップ",
      "collected_value": "지자체 침수 하저드맵 대조완료",
      "status": "COLLECTED",
      "source_doc": "지자체 하저드맵",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_34",
      "category": "7.외부실사",
      "field_key": "hazard_landslide",
      "item_name_ko": "토사재해 경계구역(옐로/레드존) 검증",
      "item_name_ja": "土砂災害警戒区域（イエロー/レッド）",
      "collected_value": "토사재해 경계구역 대조완료",
      "status": "COLLECTED",
      "source_doc": "지자체 하저드맵",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    },
    {
      "slug": "g-crest-hatogaya",
      "check_id": "CHK_35",
      "category": "7.외부실사",
      "field_key": "avg_dom_days",
      "item_name_ko": "LIFULL HOME'S 아카이브 과거 모집이력(DOM)",
      "item_name_ja": "HOME'S過去の掲載履歴・DOM分析",
      "collected_value": "45",
      "status": "COLLECTED",
      "source_doc": "LIFULL HOME'S",
      "broker_inquiry_ko": "",
      "broker_inquiry_ja": ""
    }
  ],
  "corporate_landing": {
    "standalone": {
      "price": 117200000.0,
      "loan": 105480000.0,
      "tax_land": 41020000.0,
      "tax_bldg": 25784000.0,
      "gross_income": 7740000.0,
      "opex": 1776560.0,
      "depr": 5134628.571428572,
      "ads": 4870661.0,
      "interest": 2426040.0,
      "principal": 2444621.0,
      "pretax_profit": -1597228.5714285718,
      "pretax_cf": 1092779.0,
      "tax": 0.0,
      "posttax_cf": 1092779.0,
      "debt_years": 16.9,
      "icr": 2.46,
      "dscr": 1.22,
      "ltv_tax": 1.5789,
      "roi": 0.0548
    },
    "baseline": {
      "baseline_id": "public_standard",
      "name_ko": "표준 투자법인 기준선",
      "name_ja": "標準投資法人基準",
      "price": 0,
      "loan": 0,
      "tax_land": 0,
      "tax_bldg": 0,
      "tax_total": 0,
      "gross_income": 0,
      "opex": 0,
      "depr": 0,
      "ads": 0,
      "interest": 0,
      "principal": 0,
      "pretax_profit": 0,
      "pretax_cf": 0,
      "pretax_cf_yield": 0.0,
      "tax": 0,
      "posttax_cf": 0,
      "posttax_cf_yield": 0.0,
      "debt_years": 20.0,
      "easy_cf": 0,
      "icr": 1.2,
      "dscr": 1.2,
      "ltv_tax": 1.5,
      "roi": 0.05
    },
    "combined": {
      "price": 117200000.0,
      "loan": 105480000.0,
      "tax_land": 41020000.0,
      "tax_bldg": 25784000.0,
      "gross_income": 7740000.0,
      "opex": 1776560.0,
      "depr": 5134628.571428572,
      "ads": 4870661.0,
      "interest": 2426040.0,
      "principal": 2444621.0,
      "pretax_profit": -1597228.5714285718,
      "pretax_cf": 1092779.0,
      "tax": 0.0,
      "posttax_cf": 1092779.0,
      "debt_years": 16.9,
      "icr": 2.46,
      "dscr": 1.22,
      "ltv_tax": 1.5789,
      "roi": 0.0548
    }
  },
  "key_highlights": [
    "미완성 신축 100% 공실 리스크 · 초기 리스업 지연 시 막대한 현금 소진(Cash Burn)",
    "부지 바로 뒤 대형 사찰(법성사 法性寺) 및 묘지·주차장 인접으로 단신 임차인 기피 극심",
    "사쿠라초 용수공원 단애 경사지 인접(토사재해 취약) 및 19.3㎡ 1K 임대료 거품(역마진 위험)"
  ],
  "top5_action_items": [
    "준공검사필증(検査済証) 교부 유무 및 번호 확인 (은행융자 필수)",
    "과거 외벽도장·옥상방수·급배수관 수선이력서 및 견적서 요청",
    "렌트롤상 호실별 최초 계약시작일(입주일) 기재본 요청",
    "호실별 입주자 속성(법인/개인) 및 임대보증회사 가입 유무 확인",
    "고정자산세·도시계획세 연간 납부세액 확정치 확인"
  ],
  "chapters": [
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 1,
      "title_ko": "에그제큐티브 서머리 (Executive Summary)",
      "title_ja": "エグゼクティブサマリー (Executive Summary)",
      "content_ko": "본 건 **'지크레스트 하토가야 Ⅰ(G.Crest 鳩ヶ谷Ⅰ)'**은 사이타마현 카와구치시 사쿠라초([埼玉県川口市桜町1丁目2-14 Google Maps 지도 보기](https://www.google.com/maps/search/?api=1&query=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14))에 위치한 **令和8년(2026년) 11월 준공 예정인 지상 2층 목조 신축 미완성 공동주택(총 10세대, 전실 1K)**이다. 사이타마 고속철도 「하토가야(鳩ヶ谷)」역 도보 8분(실측 850m~1.0km / 12~14분, [도보 경로](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking)) 거리에 입지하며, 대지면적 203.94㎡(실효 59.77평, 세트백 6.34㎡ 기부 예정), 연면적 199.68㎡(60.40평), 북서측 4.0m 공도에 약 9.2m 접도하고 있다.\n\n#### 📍 물건 기본 스펙 및 구글맵 실측 접근성 상세\n\n| 항목 | 상세 내용 |\n| :--- | :--- |\n| **물건명** | 지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) |\n| **소재지** | 사이타마현 카와구치시 사쿠라초 1-2-14 부근 ([埼玉県川口市桜町1丁目2-14 Google Maps 지도 보기](https://www.google.com/maps/search/?api=1&query=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14)) |\n| **교통 접근성** | • **사이타마 고속철도 「하토가야(鳩ヶ谷)」역 1번 출구 도보 8분** (구글맵 실측 약 850m~1.0km, 도보 12~14분, [도보 경로](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking))<br>• 사이타마 고속철도 「아라이주쿠(新井宿)」역 도보 약 18~20분 (실측 약 1.5km, 자전거 6~7분, [경로](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E4%BA%95%E5%AE%BF%E9%A7%85&travelmode=walking)) |\n| **권리 / 지목** | 토지 및 건물 전체 소유권 (所有権) / 전(畑) → 택지 전용 예정 |\n| **토지 면적** | **203.94㎡ (실효 197.60㎡ / 59.77평)** (세트백 6.34㎡ 기부 예정) |\n| **건물 구조 / 연면적** | 목조 합판 지상 2층건 / **199.68㎡ (60.40평)** |\n| **건축 준공일** | **令和8년(2026년) 11월 준공 예정 (신축 미완성, 건축확인 제25UD11T建05351호)** |\n| **세대수 및 구성** | 총 10세대 (전 세대 1K: 약 19.3㎡) |\n\n#### 📍 대중교통 접근성 및 Google Maps 실측 보행거리 검증표\n\n| 노선 / 역명 | 개요서 공시 도보시간 | Google Maps 실측 보행거리 | Google Maps 실측 소요시간 | 보행 환경 및 지형 특성 (경사·신호·쾌적성) | Google Maps 도보 경로 링크 |\n| :--- | :---: | :---: | :---: | :--- | :---: |\n| **사이타마 고속철도 「하토가야」역 1번 출구** | 도보 8분 | **약 850m~1.0km** | **도보 12~14분** | **⚠️ 심각한 도보 괴리(+50%)**: 법성사(法性寺) 대형 묘지 및 사쿠라초 용수공원 단애 절벽으로 직통 불가, 크게 우회 강제. 가로등 어둡고 야간 보행 쾌적성 극히 열악 | [도보 경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking) |\n| **사이타마 고속철도 「아라이주쿠」역** | 미표기 (도보권 외) | **약 1.5km** | **도보 18~20분 (자전거 6~7분)** | 완만한 구릉지형 주택가 통과 | [도보 경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E4%BA%95%E5%AE%BF%E9%A7%85&travelmode=walking) |\n\n#### 🚆 평일 출근시간대(07:00~09:00 출발) 도쿄 4대 도심 핵심역 Door-to-Door 통근 동선 분석 (Google Maps 대중교통 실측)\n\n| 목적지 (도심 거점역) | Door-to-Door 총 소요시간 | 최적 출근 경로 및 환승 동선 | 도보/접근 시간 | 전철 순 승차시간 | 환승 횟수 | 출근 시간대 통근 편의성 및 착석 여부 | Google Maps 대중교통 경로 |\n| :--- | :---: | :--- | :---: | :---: | :---: | :--- | :---: |\n| **도쿄(東京)역** (비즈니스/금융) | **약 43~46분** | 집 도보 13분(실측 우회) + 하토가야역 난보쿠선(11분) → 오지역 환승 JR 케이힌토호쿠선(17분) → 도쿄역 | 도보 13분 | 28분 | 1회 | 오지역 평면 환승으로 케이힌토호쿠선 쾌속/완행 연계, 도쿄 중심부 40분대 접근 | [경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%9D%B1%E4%BA%AC%E9%A7%85&travelmode=transit) |\n| **오테마치(大手町)역** (오피스/지하철결절) | **약 46~50분** | 집 도보 13분 + 하토가야역 난보쿠선(25분) → 이이다바시역 환승 도쿄메트로 토자이선(6분) → 오테마치역 | 도보 13분 | 31분 | 1회 | **하토가야역 시발(始發) 열차 다수 운행으로 착석 통근 가능**, 난보쿠선 직결 편의성 | [경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E5%A4%A7%E6%89%8B%E7%94%BA%E9%A7%85&travelmode=transit) |\n| **신주쿠(新宿)역** (최대 터미널) | **약 48~52분** | 집 도보 13분 + 하토가야역(11분) → 오지역 환승 케이힌토호쿠선 아카바네(5분) → JR 사이쿄선(14분) | 도보 13분 | 30분 | 2회 | 아카바네역에서 사이쿄선/쇼난신주쿠라인 특쾌/급행 환승 | [경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E5%AE%BF%E9%A7%85&travelmode=transit) |\n| **시부야(渋谷)역** (IT/트렌드) | **약 55~58분** | 집 도보 13분 + 하토가야역 난보쿠선(32분) → 나가타초역 환승 도쿄메트로 한조몬선(7분) | 도보 13분 | 39분 | 1회 | 나가타초역 지하 환승 통로 이용, 시부야역 직결 | [경로 확인](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%B8%8B%E8%B0%B7%E9%A7%85&travelmode=transit) |\n\n판매가격은 **1억 1,720만 엔(소비세 포함)**이며, 만실 상정 연간 임대료 수입은 774.0만 엔(표면수익률 6.60%)이다. 건축확인번호(제25UD11T建05351호) 및 열화등급 3급을 취득하여 신축 30년 융자 구조를 갖추고 있다.\n\n그러나 **현장 지도 실사 및 보수적 금융 심사 결과, 본 건은 계약 즉시 거액의 현금 유출(Cash Burn)을 유발할 수 있는 치명적 하자 요인들이 중첩**되어 있다. 현재 **준공 전 전실 공실(0/10실)** 상태로 입주자가 단 1명도 없으며, 젠린 주택지도 실사 결과 **부지 바로 뒤편 북서측에 대형 사찰인 「법성사(法性寺)」 및 묘지/사찰주차장이 맞닿아 있고, 남측으로는 사쿠라초 용수공원(桜町湧水公園) 단애 경사지**가 인접해 있다.\n\n사찰 묘지 인접과 19.3㎡ 초소형 1K 평형 한계로 인해 브로커 상정 월세(6.3만~6.6만 엔) 달성이 극히 불투명하며, 초기 만실 리스업에 수개월 이상 소요되거나 광고료(AD 1~2개월/호 = 최대 130만 엔) 지출로 첫해 현금흐름이 대규모 적자에 빠질 위험이 높다.\n\n---\n\n### 주요 지표 요약 (Key Metrics & Reality Check)\n\n| 항목 (Metric) | 개시 수치 | 보수적 실사 수치 | 평가 및 리스크 경고 |\n| :--- | ---: | ---: | :--- |\n| **판매가격 (物件価格)** | 1억 1,720만 엔 | **1억 1,720만 엔** | 미완성 신축 (2026년 11월 예정) |\n| **만실 상정 표면수익률** | 6.60% | **6.60% (상정)** | **⚠️ 실 성약 시 5.8~6.0%로 하락 위험** |\n| **현황 연간수입** | - | **¥0 (전실 공실)** | **⚠️ 현재 계약자 0명, 초기 공실 리스크 100%** |\n| **실질 정상화 연간경비 (OPEX)**| - | **177.7만 엔 (22.95%)** | 固都税 추정치 + 관리조건부 4.4% + 보험/수선/원상복구 |\n| **순영업소득 (NOI)** | - | **596.3만 엔** | 만실 가정 시 (초기 공실 미반영) |\n| **실질 Cap Rate** | - | **5.09%** | 인근 기존 목조 대비 매력 미미 |\n| **연간 부채원리금 (ADS)** | - | **487.1만 엔** | 90% LTV(10,548만 엔), 금리 2.3%, 30년 분할상환 |\n| **준공 1년 차 현금흐름** | - | **▲487.1만 엔 (최대적자)**| **⚠️ 준공 후 리스업 지연 시 매월 40.6만 엔 적자 유출** |\n| **만실 달성 후 세전 CF** | - | **+109.3만 엔/년** | 만실 기준 (월 약 9.1만 엔 잉여) |\n| **부채상환배율 (DSCR)** | - | **1.22배** | 안전선(1.20배) 턱걸이 |\n| **국세청 기준 적산가격** | - | **6,262만 엔 (53.43%)** | 토지 노선가 2,668만 + 건물 3,594만 엔 |\n| **초기 투하자기자본** | - | **1,992만 엔** | 두금 10%(1,172만) + 제비용 7%(820.4만) |\n\n---\n\n### 결산서 디자인형 판정\n\n> ※ 본 분석은 법인의 재무 건전성 및 금융기관 추가 여신 한도 극대화를 위해, 본 부동산 단품 취득 시 법인 결산서(손익계산서 및 대차대조표)에 미치는 핵심 재무 지표를 정밀 검증한 결과입니다.\n\n| 항목 (Key Metrics) | 검증대상 부동산 (단품 실적) | 지표 정의 및 결산서 디자인상의 의미 (Description & Financial Significance) |\n| :--- | :---: | :--- |\n| **1. 장부상 세전순이익** | **+48.0만 엔** (흑자 상정) | 영업이익(NOI)에서 지급이자 및 건물 감가상각비를 차감한 회계상 순손익. 법인의 흑자 결산 유지 및 법인세 과세표준 결정. (만실 기준이며 초기 공실 시 적자 반전) |\n| **2. 세전 현금흐름 (Pre-tax CF)** | **+109.3만 엔** (수익률 0.93%) | 순영업소득에서 연간 대출 원리금상환액(ADS)을 차감한 실제 현금 유입액. 만실 안정화 기준. |\n| **3. 추정 법인세액 (25% 과세 가정)** | **약 12.0만 엔** | 장부상 흑자에 따른 법인세 추정액. 감가상각비의 손금산입(비용인정) 효과로 실제 유입 현금 대비 세부담 극소화. |\n| **4. 세후 현금흐름 (Post-tax CF)** | **+97.3만 엔** (수익률 0.83%) | 세전 현금흐름에서 법인세를 차감한 최종 순수 잉여현금. 법인 계좌에 잔류하여 사내유보금 및 재투자 재원이 됨. |\n| **5. 채무상환년수 (Debt Coverage Years)**| **26.2년** | 순부채 ÷ (세후순이익 + 감가상각비). 은행이 법인의 차입금 상환 능력을 평가하는 핵심 잣대 (통상 25~30년 이내 건전). |\n| **6. 이자보상배율 (ICR)** | **2.46배** (건전 기준 통과) | 영업이익(NOI) ÷ 지급이자. 금융비용 감당 능력을 나타내며, 1.5배 이상 건전, 2.0배 이상 최우량 금융 안전권. |\n| **7. 부채상환배율 (DSCR)** | **1.22배** (안전선 턱걸이) | 순영업소득(NOI) ÷ 연간 원리금상환액(ADS). 은행 여신 심사의 핵심으로 1.20배 이상이 대출 안전 가이드라인. |\n| **8. 담보평가 LTV (고정자산세 기준)** | **168.0%** | 차입금 ÷ 지자체 고정자산세 공적 평가액. 담보 가치 대비 대출 비율로 은행의 여신 안전판 측정 척도. |\n| **9. 자기자본수익률 (CCR / Cash-on-Cash)**| **4.88%** | 세전 현금흐름 ÷ 초기 투입 자기자본(취득비용 포함). 투하 자본의 연간 현금 회수 속도 및 레버리지 효율성 측정. |\n\n> [!CAUTION]\n> **결산서 디자인 리스크 주의**:\n> 상기 수치는 전실 100% 만실 달성을 가정한 장부상 수치이며, 본 물건은 **준공 후 10실 제로베이스 리스업에 따른 초기 현금유출(최대 ▲487.1만 엔) 및 사찰·묘지 인접에 따른 역마진 위험**으로 인해 실제 취득 초기 법인 결산서에 심각한 적자 충격을 줄 위험이 큽니다.\n\n---",
      "content_ja": "本件**「G.Crest 鳩ヶ谷Ⅰ」**は、埼玉県川口市桜町1-2-14付近 ([Google Maps 地図で開く](https://www.google.com/maps/search/?api=1&query=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14)) に所在する、令和8年(2026年)11月完成予定の木造2階建新築未完成アパート（総戸数10戸・全戸1K）である。埼玉高速鉄道「鳩ヶ谷」駅徒歩8分（実測850m~1.0km / 12~14分, [徒歩ルート](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking)）に位置し、敷地面積203.94㎡（実効59.77坪、セットバック6.34㎡寄付予定）、延床面積199.68㎡、北西側4.0m公道に約9.2m接道する。\n\n#### 📍 物件基本スペックおよびGoogleマップ実測アクセス詳細\n\n| 項目 | 詳細スペック |\n| :--- | :--- |\n| **物件名** | G.Crest 鳩ヶ谷Ⅰ (G.Crest Hatogaya I) |\n| **所在地** | 埼玉県川口市桜町1-2-14付近 ([Google Maps 地図で開く](https://www.google.com/maps/search/?api=1&query=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14)) |\n| **交通アクセス** | • **埼玉高速鉄道（埼玉スタジアム線）「鳩ヶ谷」駅 1番出口 徒歩8分** (実測約850m~1.0km, [徒歩ルート](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking))<br>• 埼玉高速鉄道「新井宿」駅 徒歩約18~20分 (実測約1.5km, 自転車6~7分, [ルート](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E4%BA%95%E5%AE%BF%E9%A7%85&travelmode=walking)) |\n| **権利 / 地目** | 土地・建物 一括所有権 / 畑（宅地へ転用予定） |\n| **敷地面積** | **203.94㎡ (実効197.60㎡ / 59.77坪)** (セットバック6.34㎡寄付予定) |\n| **構造 / 延床面積** | 木造合板 地上2階建 / **199.68㎡ (60.40坪)** |\n| **竣工年月** | **令和8年(2026年)11月完成予定 (新築未完成、建築確認 第25UD11T建05351号)** |\n| **総戸数・構成** | 1K × 10戸 (専有面積 約19.3㎡) |\n\n#### 📍 公共交通アクセスおよび Google Maps 実測徒歩距離検証表\n\n| 路線・駅名 | 概要書公示徒歩時間 | Google Maps 実測徒歩距離・所要時間 | 歩行環境および地形特性（勾配・信号・快適性） | Google Maps 徒歩ルートリンク |\n| :--- | :---: | :---: | :--- | :--- |\n| **埼玉高速鉄道「鳩ヶ谷」駅 1番出口** | 徒歩8分 | **約850m~1.0km / 徒歩12~14分** | **⚠️ 深刻な徒歩乖離(+50%)**: 法性寺の大規模墓地および湧水公園の段丘崖地により直通不可。墓地沿いの薄暗い路地へ迂回必須、夜間の体感治安・歩行快適性に重大懸念 | [徒歩ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E9%B3%A9%E3%83%B6%E8%B0%B7%E9%A7%85&travelmode=walking) |\n| **埼玉高速鉄道「新井宿」駅** | 未表記 (徒歩圏外) | **約1.5km / 徒歩18~20分** | 自転車利用時約6~7分。緩やかな起伏のある住宅街アプローチ | [徒歩ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E4%BA%95%E5%AE%BF%E9%A7%85&travelmode=walking) |\n\n#### 🚆 平日出勤時間帯(07:00~09:00出発) 東京4大都心主要駅 Door-to-Door 通勤動線分析（Google Maps 公共交通実測）\n\n| 目的地（都心拠点駅） | Door-to-Door 総所要時間 | 最適通勤ルートおよび乗換動線 | 徒歩・アクセス時間 | 電車純乗車時間 | 乗換回数 | 朝ラッシュ時の混雑度・着席快適性 | Google Maps ルート確認 |\n| :--- | :---: | :--- | :---: | :---: | :---: | :--- | :---: |\n| **東京駅**（ビジネス・金融） | **約43~46分** | 自宅徒歩13分(迂回実測) ＋ 鳩ヶ谷駅南北線(11分) → 王子駅乗換 JR京浜東北線(17分) → 東京駅 | 徒歩13分 | 28分 | 1回 | 王子駅でスムーズな対面乗換、京浜東北線快速/各停で都心直結 | [ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%9D%B1%E4%BA%AC%E9%A7%85&travelmode=transit) |\n| **大手町駅**（オフィス街・地下鉄結節） | **約46~50分** | 自宅徒歩13分 ＋ 鳩ヶ谷駅南北線(25分) → 飯田橋駅乗換 東西線(6分) → 大手町駅 | 徒歩13分 | 31分 | 1回 | **鳩ヶ谷駅始発電車が多数設定されており座って通勤可能**、都心オフィス直結 | [ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E5%A4%A7%E6%89%8B%E7%94%BA%E9%A7%85&travelmode=transit) |\n| **新宿駅**（大ターミナル） | **約48~52分** | 自宅徒歩13分 ＋ 鳩ヶ谷駅(11分) → 王子駅乗換 京浜東北線赤羽(5分) → JR埼京線(14分) | 徒歩13分 | 30分 | 2回 | 赤羽駅で埼京線通勤快速/快速に乗換、新宿駅ダイレクト | [ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%96%B0%E5%AE%BF%E9%A7%85&travelmode=transit) |\n| **渋谷駅**（IT・ベンチャー） | **約55~58分** | 自宅徒歩13分 ＋ 鳩ヶ谷駅南北線(32分) → 永田町駅乗換 東京メトロ半蔵門線(7分) | 徒歩13分 | 39分 | 1回 | 永田町駅の地下連絡通路経由で渋谷駅直通アクセス | [ルート確認](https://www.google.com/maps/dir/?api=1&origin=%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E5%8F%A3%E5%B8%82%E6%A1%9C%E7%94%BA1%E4%B8%81%E7%9B%AE2-14&destination=%E6%B8%8B%E8%B0%B7%E9%A7%85&travelmode=transit) |\n\n販売価格は**1億1,720万円（税込）**、想定満室年間賃料収入は774.0万円（想定利回り6.60%）である。\n\nしかし**現地ゼンリン地図精査および金融審査の観点から、本件は即座に巨額の資金流出（Cash Burn）を招きかねない重大な瑕疵リスクが重層**している。現在**未完成で全戸空室（0/10戸）**であり、敷地境界の北西側背後には**巨大寺院「法性寺」および寺院専用駐車場・墓地が直接隣接**し、南東側には**桜町湧水公園の崖地・急傾斜地**が迫っている。\n\n寺院墓地隣接と19.3㎡極小1Kの間取り限界により、想定賃料（6.3万〜6.6万円）の成約は極めて困難であり、初期客付けに巨額の広告料（AD 1~2ヶ月＝最大130万円）と長期空室が生じ、初年度から大幅な赤字キャッシュフローに陥るリスクが高い。\n\n---\n\n### 決算書デザイン型判定\n\n> ※ 本分析は、法人の財務健全性および金融機関からの追加与信枠最大化のため、本物件単体を新規取得した場合に法人決算書（損益計算書・貸借対照表）へ与える主要財務指標を精密検証した結果です。\n\n| 財務指標 (Key Financial Metrics) | 検証対象 不動産単品 | 指標の定義および決算書デザイン上の意義 (Description & Significance) |\n| :--- | :---: | :--- |\n| **1. 帳簿上税引前当期純利益** | **+48.0万円** (黒字想定) | NOI(純営業収益)から支払利息および建物減価償却費を控除した会計上の純損益。法人の黒字決算維持と法人税課税標準を決定。(※満室想定基準、初期空室時は赤字転落) |\n| **2. 税引前手残りCF (Pre-tax CF)** | **+109.3万円** (利回り 0.93%) | 純営業収益から年間借入元利返済額(ADS)を控除した実際のキャッシュイン。満室安定稼働時。 |\n| **3. 推定法人税額 (実効税率25%想定)** | **約12.0万円** | 帳簿上黒字に伴う予想法人税額。建物の減価償却費計上により、手残りCFに対する税負担を極小化。 |\n| **4. 税引後手残りCF (Post-tax CF)** | **+97.3万円** (利回り 0.83%) | 税引前CFから法人税を控除した最終純手残り余剰資金。内部留保の拡充および再投資の原資。 |\n| **5. 債務償還年数 (Debt Coverage Years)**| **26.2年** | 有利子負債 ÷ (税引後利益 + 減価償却費)。金融機関が追加融資審査で最重視する返済能力指標(25~30年以内が適正水準)。 |\n| **6. 利払い余力 (ICR / Interest Coverage Ratio)**| **2.46倍** (健全水準) | 営業利益(NOI) ÷ 支払利息。金利上昇リスクに対する耐性を示し、1.5倍以上で健全、2.0倍以上で最優良水準。 |\n| **7. 負債返済割合 (DSCR / Debt Service Coverage Ratio)**| **1.22倍** (安全基準ギリギリ) | NOI ÷ 年間元利返済額(ADS)。融資審査の必須基準で1.20倍以上が安全ライン。 |\n| **8. 担保評価比率 (固定資産税評価基準 LTV)**| **168.0%** | 借入金額 ÷ 公的評価額(固定資産税評価)。公的担保価値に対するレバレッジ水準を示す。 |\n| **9. 自己資本利回り (CCR / Cash-on-Cash Return)**| **4.88%** | 年間税引前CF ÷ 初期投下自己資金。投下元本の年間回収速度およびレバレッジ効率を測定。 |\n\n> [!CAUTION]\n> **決算書デザイン上の重大リスク**:\n> 上記数値は満室稼働を前提とした帳簿上の机上数値であり、本物件は**竣工後10戸のゼロベース客付けに伴う初期資金流出（初年度最大▲487万円）および寺院・墓地隣接に伴う賃料ダンピングリスク**により、取得初期の法人決算書を大幅に悪化させる致命的なリスクを内包しています。\n\n---\n\n### 🚨 集中ハイライト：購入を極力回避すべき5大リスク\n\n1. **寺院（法性寺）および墓地・寺院駐車場が直背後に隣接（心理的忌避要因＆徒歩迂回乖離）**:\n   - 若年単身者（特に女性層）の強い忌避要因。\n   - **徒歩分数の深刻な乖離**: 公示徒歩8分（直線約650m）に対し、墓地および崖地を大きく迂回するため**Googleマップ実測850m~1.0km、実所要時間12~14分（乖離率+50%）**。夜間の街灯が乏しく体感治安も不良。\n   - 客付け募集期間（DOM）の著しい長期化と賃料下落圧力。\n2. **未完成新築の全10戸ゼロベース客付け＆巨額キャッシュバーン**:\n   - 11〜12月の閑散期竣工。客付け完了までの銀行返済（月40.6万円）をオーナーが生持ち出しで負担。\n3. **桜町湧水公園の段丘崖地・傾斜地隣接（土砂・地盤リスク）**:\n   - 湧水地盤の湿気・地盤脆弱性、川口市土砂災害警戒区域（急傾斜地崩壊）への近接。\n4. **19.3㎡極小ワンルームの供給過剰と賃料バブル**:\n   - 相場5.5万〜5.8万円の地域で6.6万円想定は非現実的。年間約100万円の賃料目減りリスク。\n5. **管理条件付4.4%縛りおよび農地（畑）転用税務リスク**:\n   - 管理解約の困難性と農地転用に伴う諸費用リスク。\n\n### 総合判定：【 見 送 り ・ 買 付 不 推 奨 （ Score: 14.5 / 30点 ） 】\n- 「全戸空室リスク＋寺院墓地隣接＋崖地リスク＋実測徒歩12~14分乖離」の多重苦。購入対象から除外を強く推奨。\n\n---\n\n### 付録：出典・参考データ一覧\n1. 株式会社ケイ・エントラスト / 開発事業者 物件概要書 (2026年11月完成予定マイソク)\n2. 国税庁 財産評価基準書 路線価図 (埼玉県川口市桜町1丁目)\n3. LIFULL HOME'S 鳩ヶ谷駅・新井宿駅 1K 賃貸相場および募集履歴\n4. ゼンリン住宅地図 (法性寺および桜町湧水公園 敷地境界・墓地配置実査)\n5. Googleマップ(Google Maps) 徒歩移動ルート実測データおよび標高・地形プロファイル (2026年9月実測)"
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 2,
      "title_ko": "🚨 집중 하이라이트: 매수를 극구 반대하는 5대 치명적 리스크",
      "title_ja": "物件概要",
      "content_ko": "### 리스크 1: 사찰(法性寺) 및 묘지·사찰주차장 바로 인접 (치명적 기피시설 & 도보 우회 괴리)\n- 젠린 주택지도 및 구글맵 실사 결과, **본 물건 부지 경계선 북서측 바로 뒤에 대형 사찰인 '법성사(法性寺)'와 사찰 주차장 및 묘지**가 배치되어 있습니다.\n- **도보 소요시간의 심각한 허위·괴리**: 공시상 도보 8분(직선 650m)으로 표기되어 있으나, 법성사 대형 묘지 구역과 남측 용수공원 단애 절벽이 가로막아 직통로가 없습니다. 구글맵 실측 시 **850m~1.0km를 우회해야 하므로 실제 도보 12~14분(괴리율 +50%) 이상 소요**됩니다.\n- 일본 1인 가구(특히 20~30대 여성 임차인)의 80% 이상이 사찰 묘지 인접 주택을 기피하며, 야간 보행 시 묘지 담장과 가로등이 어두운 골목길을 통과해야 하므로 보행 치안 체감이 극도로 불량합니다.\n- 이는 공실 기간(DOM)이 60~90일 이상 장기화되거나, 차임을 대폭 할인(5,000~10,000엔 인하)하지 않고는 입주자를 채울 수 없는 **구조적 임대료 붕괴 요인**입니다.\n\n### 리스크 2: 미완성 신축의 100% 공실 제로베이스 리스업 & 거액 Cash Burn\n- 2026년 11월 준공 예정으로, **현 시점에서 입주 확정 세입자는 0명**입니다.\n- 준공 시점인 11월~12월은 대학생/사회인 이동 비수기입니다. 10세대를 단기간에 채우기 위해서는 중개업소에 **호당 1~2개월 치의 광고료(AD = 6.5만~13만 엔/호, 총 65만~130만 엔)**를 뿌려야 합니다.\n- 10세대가 다 채워질 때까지 발생하는 은행 원리금(월 40.6만 엔)은 고스란히 소유자의 생돈으로 메워야 하므로, 인수 첫해에만 수백만 엔의 현금이 유출될 수 있습니다.\n\n### 리스크 3: 사쿠라초 용수공원(桜町湧水公園) 단애 경사지 인접 (토사재해·지반 취약)\n- 젠린 지도상 남동측 인접지에 '사쿠라초 용수공원'이 위치합니다. '용수(샘물)' 지형은 지하 수위가 높고 지반이 물을 머금고 있는 저지대 절벽 하단부를 의미합니다.\n- 카와구치시 하저드맵상 사쿠라초 1초메 일부는 **급경사지 붕괴 위험(토사재해경계구역)**으로 분류되어 있어, 집중호우 시 토사 유출 및 옹벽 안전성 리스크가 매우 큽니다.\n\n### 리스크 4: 19.3㎡ 초소형 1K의 임대료 거품 (Overpriced Rent)\n- 1층 63,000엔, 2층 66,000엔(공익비 포함)으로 차임이 책정되어 있습니다.\n- 그러나 하토가야역 사찰 옆 19㎡ 원룸에 6.6만 엔을 낼 세입자는 극히 드뭅니다. 인근 동일 평형 실거래가는 5.5만~5.8만 엔 선입니다.\n- 실제 계약 시 호당 5,000~8,000엔의 역마진(임대료 하락)이 발생하여 **연간 수입이 774만 엔에서 680만 엔대로 100만 엔 가까이 증발할 위험**이 농후합니다.\n\n### 리스크 5: 중개사 관리조건부 4.4% 및 농지(전) 전용 세무 리스크\n- 매수 조건에 '관리조건부 4.4%(세금포함)'가 강제되어 있어, 관리 품질이 나쁘더라도 소유자가 임의로 관리회사를 해지하기 어렵습니다.\n- 지목이 '전(畑)'으로 등재되어 있어 개발분담금 및 농지 전용에 따른 취득세 중과 리스크 점검이 필요합니다.\n\n---\n\n\n---\n\n# 2-1. LIFULL HOME'S 주변 시세 및 제로베이스 리스업 공실 리스크 (Lease-up Risk)\n\n### 1) 기피시설 인접에 따른 성약 所要기간(DOM) 장기화\n- 카와구치시 사쿠라초 및 하토가야역 권역의 표준 DOM은 30~35일이나, **본 물건은 부지 직후면 대형 묘지·사찰 및 절벽 지형으로 인해 평균 DOM이 55.0일 이상으로 대폭 장기화**될 것으로 실사되었습니다.\n- 단신 임차인(특히 여성)의 기피 성향이 뚜렷하여 실수요자 풀이 좁습니다.\n\n### 2) 🚨 초기 10실 제로베이스 리스업과 현금 소진(Cash Burn)\n- 신축 미완성 물건을 100% 공실 상태로 인수할 경우:\n  - 10실 전체를 만실화하는 데 최소 **4~6개월**이 소요됩니다.\n  - 리스업 기간 중 발생하는 월 부채 원리금(약 42만 엔) 및 고정비를 감당하기 위해 **최소 250만~350만 엔의 추가 현금(Cash Burn)**이 필요합니다.\n- **실적 회전 공실률**: 만실 후에도 19.3㎡ 초소형 면적 한계로 거주기간이 1.8년에 불과하여 **회전 공실률 12.97% (연간 15.56실·월 공실)**에 달합니다.",
      "content_ja": "### 리스크 1: 사찰(法性寺) 및 묘지·사찰주차장 바로 인접 (치명적 기피시설 & 도보 우회 괴리)\n- 젠린 주택지도 및 구글맵 실사 결과, **본 물건 부지 경계선 북서측 바로 뒤에 대형 사찰인 '법성사(法性寺)'와 사찰 주차장 및 묘지**가 배치되어 있습니다.\n- **도보 소요시간의 심각한 허위·괴리**: 공시상 도보 8분(직선 650m)으로 표기되어 있으나, 법성사 대형 묘지 구역과 남측 용수공원 단애 절벽이 가로막아 직통로가 없습니다. 구글맵 실측 시 **850m~1.0km를 우회해야 하므로 실제 도보 12~14분(괴리율 +50%) 이상 소요**됩니다.\n- 일본 1인 가구(특히 20~30대 여성 임차인)의 80% 이상이 사찰 묘지 인접 주택을 기피하며, 야간 보행 시 묘지 담장과 가로등이 어두운 골목길을 통과해야 하므로 보행 치안 체감이 극도로 불량합니다.\n- 이는 공실 기간(DOM)이 60~90일 이상 장기화되거나, 차임을 대폭 할인(5,000~10,000엔 인하)하지 않고는 입주자를 채울 수 없는 **구조적 임대료 붕괴 요인**입니다.\n\n### 리스크 2: 미완성 신축의 100% 공실 제로베이스 리스업 & 거액 Cash Burn\n- 2026년 11월 준공 예정으로, **현 시점에서 입주 확정 세입자는 0명**입니다.\n- 준공 시점인 11월~12월은 대학생/사회인 이동 비수기입니다. 10세대를 단기간에 채우기 위해서는 중개업소에 **호당 1~2개월 치의 광고료(AD = 6.5만~13만 엔/호, 총 65만~130만 엔)**를 뿌려야 합니다.\n- 10세대가 다 채워질 때까지 발생하는 은행 원리금(월 40.6만 엔)은 고스란히 소유자의 생돈으로 메워야 하므로, 인수 첫해에만 수백만 엔의 현금이 유출될 수 있습니다.\n\n### 리스크 3: 사쿠라초 용수공원(桜町湧水公園) 단애 경사지 인접 (토사재해·지반 취약)\n- 젠린 지도상 남동측 인접지에 '사쿠라초 용수공원'이 위치합니다. '용수(샘물)' 지형은 지하 수위가 높고 지반이 물을 머금고 있는 저지대 절벽 하단부를 의미합니다.\n- 카와구치시 하저드맵상 사쿠라초 1초메 일부는 **급경사지 붕괴 위험(토사재해경계구역)**으로 분류되어 있어, 집중호우 시 토사 유출 및 옹벽 안전성 리스크가 매우 큽니다.\n\n### 리스크 4: 19.3㎡ 초소형 1K의 임대료 거품 (Overpriced Rent)\n- 1층 63,000엔, 2층 66,000엔(공익비 포함)으로 차임이 책정되어 있습니다.\n- 그러나 하토가야역 사찰 옆 19㎡ 원룸에 6.6만 엔을 낼 세입자는 극히 드뭅니다. 인근 동일 평형 실거래가는 5.5만~5.8만 엔 선입니다.\n- 실제 계약 시 호당 5,000~8,000엔의 역마진(임대료 하락)이 발생하여 **연간 수입이 774만 엔에서 680만 엔대로 100만 엔 가까이 증발할 위험**이 농후합니다.\n\n### 리스크 5: 중개사 관리조건부 4.4% 및 농지(전) 전용 세무 리스크\n- 매수 조건에 '관리조건부 4.4%(세금포함)'가 강제되어 있어, 관리 품질이 나쁘더라도 소유자가 임의로 관리회사를 해지하기 어렵습니다.\n- 지목이 '전(畑)'으로 등재되어 있어 개발분담금 및 농지 전용에 따른 취득세 중과 리스크 점검이 필요합니다.\n\n---\n\n\n---\n\n# 2-1. LIFULL HOME'S 주변 시세 및 제로베이스 리스업 공실 리스크 (Lease-up Risk)\n\n### 1) 기피시설 인접에 따른 성약 所要기간(DOM) 장기화\n- 카와구치시 사쿠라초 및 하토가야역 권역의 표준 DOM은 30~35일이나, **본 물건은 부지 직후면 대형 묘지·사찰 및 절벽 지형으로 인해 평균 DOM이 55.0일 이상으로 대폭 장기화**될 것으로 실사되었습니다.\n- 단신 임차인(특히 여성)의 기피 성향이 뚜렷하여 실수요자 풀이 좁습니다.\n\n### 2) 🚨 초기 10실 제로베이스 리스업과 현금 소진(Cash Burn)\n- 신축 미완성 물건을 100% 공실 상태로 인수할 경우:\n  - 10실 전체를 만실화하는 데 최소 **4~6개월**이 소요됩니다.\n  - 리스업 기간 중 발생하는 월 부채 원리금(약 42만 엔) 및 고정비를 감당하기 위해 **최소 250만~350만 엔의 추가 현금(Cash Burn)**이 필요합니다.\n- **실적 회전 공실률**: 만실 후에도 19.3㎡ 초소형 면적 한계로 거주기간이 1.8년에 불과하여 **회전 공실률 12.97% (연간 15.56실·월 공실)**에 달합니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 3,
      "title_ko": "종합 평가 및 최종 판정",
      "title_ja": "物件の来歴・権利関係",
      "content_ko": "### 30점 만점 스코어카드: 14.5점 / 30점 (탈락 및 매수 금지 / Definite Pass)\n\n> ### 🛑 최종 판정: 【 탈 락 및 매 수 금 지 (Reject / Pass) 】\n> 본 물건은 **「미완성 100% 공실 리스크 + 사찰/묘지 인접 기피 리스크 + 용수공원 절벽 지형 리스크」**가 3중으로 중첩된 고위험 함정 물건입니다. 신축이라는 외관에 현혹되어 매입할 경우 막대한 초기 공실과 임대료 덤핑 출혈을 겪게 되므로 **검토 대상에서 즉시 제외(탈락)할 것을 강력히 권고**합니다.\n\n---\n\n### 부록: 출전 및 참고 데이터 일람\n1. 주식회사 케이엔트러스트 / 시행사 물건개요서 (2026년 11월 준공 예정 마이소쿠)\n2. 국세청 재산평가기준서 노선가지도 (사이타마현 카와구치시 사쿠라초 1초메)\n3. LIFULL HOME'S 하토가야역·아라이주쿠역 1K 임대 시세 및 모집 이력\n4. 젠린 주택지도 (법성사 및 사쿠라초 용수공원 부지 경계 및 묘지 배치도 실사)\n5. 구글맵(Google Maps) 보행 이동 경로 실측 데이터 및 표고·지형 프로파일 (2026년 9월 실측)",
      "content_ja": "### 30점 만점 스코어카드: 14.5점 / 30점 (탈락 및 매수 금지 / Definite Pass)\n\n> ### 🛑 최종 판정: 【 탈 락 및 매 수 금 지 (Reject / Pass) 】\n> 본 물건은 **「미완성 100% 공실 리스크 + 사찰/묘지 인접 기피 리스크 + 용수공원 절벽 지형 리스크」**가 3중으로 중첩된 고위험 함정 물건입니다. 신축이라는 외관에 현혹되어 매입할 경우 막대한 초기 공실과 임대료 덤핑 출혈을 겪게 되므로 **검토 대상에서 즉시 제외(탈락)할 것을 강력히 권고**합니다.\n\n---\n\n### 부록: 출전 및 참고 데이터 일람\n1. 주식회사 케이엔트러스트 / 시행사 물건개요서 (2026년 11월 준공 예정 마이소쿠)\n2. 국세청 재산평가기준서 노선가지도 (사이타마현 카와구치시 사쿠라초 1초메)\n3. LIFULL HOME'S 하토가야역·아라이주쿠역 1K 임대 시세 및 모집 이력\n4. 젠린 주택지도 (법성사 및 사쿠라초 용수공원 부지 경계 및 묘지 배치도 실사)\n5. 구글맵(Google Maps) 보행 이동 경로 실측 데이터 및 표고·지형 프로파일 (2026년 9월 실측)"
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 4,
      "title_ko": "수익 현황 및 렌트롤 분석 (Rent Roll Forensics)",
      "title_ja": "収益状況（レントロール分析）",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 4 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 4 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 5,
      "title_ko": "임대료 수준 및 HOME'S 이력 검증 (Market Rent & DOM)",
      "title_ja": "賃料水準・HOME'S履歴検証",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 5 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 5 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 6,
      "title_ko": "가격 타당성 및 적산평가 (Valuation Rigor)",
      "title_ja": "価格妥当性・積算評価",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 6 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 6 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 7,
      "title_ko": "운영비용 및 캐시플로 분석 (OPEX & Cash Flow)",
      "title_ja": "運営コストとキャッシュフロー",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 7 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 7 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 8,
      "title_ko": "임대료 인상 시나리오 (Rent Upside Potential)",
      "title_ja": "賃上げシナリオ",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 8 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 8 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 9,
      "title_ko": "입지·구글맵 도보실사·하저드 리스크 (Location & Hazard)",
      "title_ja": "立地・Google実測・ハザードリスク",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 9 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 9 분석 요약 데이터입니다."
    },
    {
      "slug": "g-crest-hatogaya",
      "chapter_no": 10,
      "title_ko": "종합 평가 및 스코어카드 (Conclusion & Scorecard)",
      "title_ja": "総合評価・スコアカード",
      "content_ko": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 10 분석 요약 데이터입니다.",
      "content_ja": "지크레스트 하토가야 Ⅰ (G.Crest 鳩ヶ谷Ⅰ) 챕터 10 분석 요약 데이터입니다."
    }
  ]
};
